### ISSUE TITLE
xpath always gives empty result with string(./h2/a/text()) and concat(..........) 

### ISSUE THREAD

**Issue by abhisheksingh1** [tid-kijyun/Kanna#101]
### Description:

http://www.homedepot.com/p/Arnold-Universal-Snow-Thrower-Key-Set-4-Piece-490-241-0008/202251530?keyword=4902410008

We use this xpath:
concat(//_[@id='ajaxPrice']/text(), //_[@id='ciItemPrice']/text())
string(./h2/a/text())

Always get empty results. They all not working if i will return string as result of xpath query. Any ideas how i can return string but not XMLElement ?
### Installation method:
- [ ] CocoaPods
### Library version:
- [ ] v1.1.1
### Xcode version:
- [ ] 7.3.1

**Comment by Arti3DPlayer** [comment]
Look here:

https://github.com/tid-kijyun/Kanna/issues/40

**Comment by tid-kijyun** [comment]
Closed because it is a problem in the old version.
Feel free to repost if the issue is not resolved.
