### ISSUE TITLE
Value of type 'XPathObject' has no member 'toHTML'

### ISSUE THREAD

**Issue by picopeak** [tid-kijyun/Kanna#102]
### Description:

After upgrading to Kanna swift 3.0, I got this error "/Users/picopeak/ioshomework/homework/ViewController.swift:1219:31: Value of type 'XPathObject' has no member 'toHTML'"

How to change it?
### Installation method:
- [ ] Carthage
- [x ] CocoaPods
- [ ] Manually
### Library version:
- [ ] v1.1.1
- [ ] v1.0.6
- [ ] v1.0.2
- [x] other: (branch swift 3.0.)
### Xcode version:
- [x] 8.0 beta (Swift 3.0)
- [ ] 8.0 beta (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

**Comment by tid-kijyun** [comment]
Please use version 2.0.0.

Note:
I've just released a version 2.0.0 that fixes issues.
Please use Cocoapods 1.1.0RC or later.

```
pod 'Kanna', '~> 2.0.0'
```

**Comment by snaill** [comment]
use version 2.0.0.
but
Value of type 'XPathObject' has no member 'count'

**Comment by snaill** [comment]
`
    func xpath(html: HTMLDocument, query: String) -> Kanna.XMLNodeSet? {
        let x = html.xpath(query)
        switch x {
        case .NodeSet(let nodeset):
            return nodeset
        default:
            return nil
        }
    }
`

**Comment by snaill** [comment]
func xpath(html: HTMLDocument, query: String) -> Kanna.XMLNodeSet? {
        let x = html.xpath(query)
        switch x {
        case .NodeSet(let nodeset):
            return nodeset
        default:
            return nil
        }
    }

**Comment by tid-kijyun** [comment]
This issue was resolved in version 2.0.1.
