### ISSUE TITLE
Expression type "HTMLDocument?" is ambiguous without more context

### ISSUE THREAD

**Issue by igrrik** [tid-kijyun/Kanna#103]
### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Manually
### Library version:
- [ ] v1.1.1
- [ ] v1.0.6
- [ ] v1.0.2
- [x] other: (2.0.0)
### Xcode version:
- [ ] 8.0 beta (Swift 3.0)
- [ ] 8.0 beta (Swift 2.3)
- [ ] 7.3.1
- [x] other: (8.0 swift 3)

Hello, I'm trying to test your sample code, but there is an error "Expression type "HTMLDocument?" is ambiguous without more context" , when I'm building it. 

```
let url = URL.init(string: "http://www.google.com")
let data = NSData.init(contentsOf: url!)

if let doc = HTML(html: data, encoding: .utf8) {
    print(doc.title)
}
```

**Comment by tid-kijyun** [comment]
`NSData` has been changed to `Data`.

```
let url = URL(string: "http://www.google.com")
let data = try! Data(contentsOf: url!)
if let doc = HTML(html: data, encoding: .utf8) {
    print(doc.title)
}
```

**Comment by essineden** [comment]
hi @tid-kijyun,
I'm having the same problem with this code but it actually came from a json string. Does that matter?
