### ISSUE TITLE
if class name contains "_" result is empty

### ISSUE THREAD

**Issue by voynovia** [tid-kijyun/Kanna#104]
### Description:
if class name contains "_" result is empty

Example:
...
for link in doc.css(".catalog_container") {
...

### Installation method:
- [] CocoaPods

### Library version:
- [] v2.0.0

### Xcode version:
- [] 8.0 (Swift 3.0)

**Comment by tid-kijyun** [comment]
Hi @voynovia 

I can't reproduce this issue.
Could you be more specific?

For example:
```
let html = "<html><body><a class='catalog_container' href='index.html'>abc</a></body></html>"
if let doc = HTML(html: html, encoding: .utf8) {
    for link in doc.css(".catalog_container") {
        print(link["href"])
    }
}
```

Output:
```
Optional("index.html")
```

Thanks

**Comment by voynovia** [comment]
thanks, was my mistake
