### ISSUE TITLE
Swift 3 - Library not loaded, Reason: image not found

### ISSUE THREAD

**Issue by Giu989** [tid-kijyun/Kanna#105]
### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Manually
### Library version:
- [ ] v1.1.1
- [ ] v1.0.6
- [ ] v1.0.2
- [x] other: (2.0.0)
### Xcode version:
- [ ] 8.0 beta (Swift 3.0)
- [ ] 8.0 beta (Swift 2.3)
- [ ] 7.3.1
- [x] other: Xcode 8

I tried installing Kanna today on an empty Xcode project with Swift 3.0

The pod file I used is:

"use_frameworks!

target 'testScraper' do
    pod 'Kanna', '~> 2.0.0'
end"

Some also mentioned the need for a Cart file so I created one, added: github "tid-kijyun/Kanna" ~> 2.0.0 and then in the same directory typed in "carthage update".

However, when I try run the empty project I get the following error:

dyld: Library not loaded: @rpath/libswiftAppKit.dylib
  Referenced from: /Users/giuliocrisanti/Library/Developer/Xcode/DerivedData/testScraper-dseezlkcyhkjbnfzbiunegueriht/Build/Products/Debug/Kanna.framework/Versions/A/Kanna
  Reason: image not found
(lldb) 

my /Debug/ folder has these items in it: Folder called Kanna, Pods_testScraper.framework, testScraper (executable), folder testScraper.swift module, Kanna.framework (which i copied from the 'Debug/Kanna' folder in an attempt to see if that would change anything).

Is this a bug or am I installing wrong?

Thanks!

**Comment by tid-kijyun** [comment]
I think that it is not a bug.
Please refer to the following URL:
https://github.com/krzyzanowskim/CryptoSwift/issues/137

**Comment by lanephillips** [comment]
I tried following this answer, but got confused: https://stackoverflow.com/a/39502220

Easier solution is don't use Swift + Cocoapods for a command line tool. Just create a Cocoa application.

**Comment by tid-kijyun** [comment]
Closed because it is a problem in the old version.
Feel free to repost if the issue is not resolved.
