### ISSUE TITLE
Cannot invoke 'HTML' with an argument list of type '(html: String, encoding: UInt)'

### ISSUE THREAD

**Issue by Arti3DPlayer** [tid-kijyun/Kanna#106]
### Description:
I converted my project to swift 3. And everywhere where i use this ```Kanna.HTML(html: string, encoding: UInt)```

```
let detailPage = itemData["_DetailPage"] as? String ?? ""
let pageEncoding = itemData["_DetailPageEncoding"] as? UInt

if let doc = Kanna.HTML(html: detailPage, encoding: pageEncoding){
                
}
```
I got error:

> Cannot invoke 'HTML' with an argument list of type '(html: String, encoding: UInt)'

### Installation method:
- [x] CocoaPods

### Library version:

- [x] 2.0.0

### Xcode version:
- [x] 8.0 beta (Swift 3.0)

**Comment by tid-kijyun** [comment]
`Kanna.HTML(html: string, encoding: Uint)` is obsolete in version 2.0.0 .
Please use `Kanna.HTML(html: string, encoding: String.Encoding)` instead.

```
let detailPage = itemData["_DetailPage"] as? String ?? ""
let pageEncoding = itemData["_DetailPageEncoding"] as? Uint
let enc = String.Encoding(rawValue: pageEncoding!)
if let doc = Kanna.HTML(html: detailPage, encoding: enc) {
}
```
