### ISSUE TITLE
Incorrect decoding data for nodes swift 3

### ISSUE THREAD

**Issue by Arti3DPlayer** [tid-kijyun/Kanna#109]
### Description:

When my program was on swift 2 and use old version of library, all was fine. Now with version 2.0 and swift 3 my `xml` data decode incorrectly.

I have next code:

```
pageEncoding:String.Encoding = .utf8

guard let xmlConfing = self.defaults.object(forKey: "xmlConfing") as? Data else {
            return []
        }

guard let doc = Kanna.XML(xml: xmlConfing, encoding: pageEncoding) else {
            return []
        }

let current = doc.xpath("//ROOT/*").map({ $0 })
let siteMatches = current.xpath("./MATCHES/*").map({ $0 })

for siteMatch in siteMatches {
            print(siteMatch.toXML)
        }
```

return me`Optional("<STORE><><tem></tem></></STORE>")`

Here is my xml:

```

<ROOT>     
    <NODENAME>         
          <MATCHES>             
                <STORE>
                      <STORE_NAME>My name</STORE_NAME>
                </STORE>
           </MATCHES>
     </NODENAME>  
</ROOT> 
```

Nothing changed on server. This code worked before:(

If i do:
`let current = doc.xpath("//ROOT/*").map({ $0.toXML })`
it show correct string but with `\n` at the end of every line.

And sometimes this happens:

![screen shot 2016-10-04 at 16 33 58](https://cloud.githubusercontent.com/assets/3278913/19076188/7c0bf29a-8a50-11e6-8b46-64abc8b084bf.png)
But i'm not sure it is my problem with decoding.
### Installation method:
- [x] CocoaPods(1.1.0 or later)
### Library version:
- [X] v2.0.0
### Xcode version:
- [X] 8.0 (Swift 3.0)

**Comment by Arti3DPlayer** [comment]
help please:( can't find solution couple days

**Comment by tid-kijyun** [comment]
Hi @Arti3DPlayer 

Please check the contents of the `xmlConfing`.

```
pageEncoding:String.Encoding = .utf8

guard let xmlConfing = self.defaults.object(forKey: "xmlConfing") as? Data else {
    return []
}

// What will be displayed after this?
print(String(data: xmlConfing, encoding: pageEncoding:String.Encoding))
```

**Comment by Arti3DPlayer** [comment]
Normal html
```<ROOT>\n    <ABT>\n        <STORE_TYPE>O</STORE_TYPE>\n        <STORE_NAME>ABT</STORE_NAME>\n        <RETURN_DAYS>45</RETURN_DAYS>\n  ```

**Comment by tid-kijyun** [comment]
Please try to run the following code. Does it works correctly?

```
        let input = "<ROOT>\n        <NODENAME>\n        <MATCHES>\n        <STORE>\n        <STORE_NAME>My name</STORE_NAME>\n        </STORE>\n        </MATCHES>\n        </NODENAME>\n        </ROOT>"
        let pageEncoding:String.Encoding = .utf8
        guard let xmlConfing = input.data(using: pageEncoding) else { return }
        if let doc = XML(xml: xmlConfing, encoding: String.Encoding.utf8) {
            let current = doc.xpath("//ROOT/*").map({ $0 })
            for c in current {
                let siteMatches = c.xpath("./MATCHES/*").map({ $0 })
                for siteMatch in siteMatches {
                    print(siteMatch.toXML)
                }
            }
        }
```

**Comment by Arti3DPlayer** [comment]
No, doesn't work...

![screen shot 2016-10-08 at 09 31 37](https://cloud.githubusercontent.com/assets/3278913/19210982/141d9160-8d3a-11e6-8190-9b394ea9d9be.png)

Got exception here

**Comment by tid-kijyun** [comment]
Please try to run it in a new project.

**Comment by tid-kijyun** [comment]
Also, please try to clear a `Derived Data` on your project.

**Comment by Arti3DPlayer** [comment]
Ok, will try to create new project later. delete rm -rf ~/Library/Developer/Xcode/DerivedData/  not helped.

**Comment by Arti3DPlayer** [comment]
@tid-kijyun i created new project. Copy my xml to file. Read from file. Same issue...

**Comment by Arti3DPlayer** [comment]
Any ideas ? Here my xml:
http://pastebin.com/N0Tn7c8n

**Comment by tid-kijyun** [comment]
Does this project work?
https://github.com/tid-kijyun/ValidateKanna109

It works in my environment.

**Comment by Arti3DPlayer** [comment]
@tid-kijyun weird Your project work for me too:(

 Also, i print a lot, found something: ```artPI : target name [Xx][Mm][Ll] is reserved for xml standardization!\n```. i checked xml on online validator it is ok. Maybe i have old xmllib parser ?

**Comment by Arti3DPlayer** [comment]
ok, i found problem i think. Your library conflicts with something that has class ```XMLElement```. But ```Kanna.XMLElement``` not helping...

**Comment by Arti3DPlayer** [comment]
ok, your project crashes too

**Comment by Arti3DPlayer** [comment]
add this function:

```
func getSite(_ storeName:String, pageEncoding:String.Encoding = .utf8) -> XMLElement? {
            guard let storeConfig = UserDefaults.standard.object(forKey: "storeConfig") as? Data else {             return nil
            }
            guard let doc = Kanna.XML(xml: storeConfig, encoding: pageEncoding) else {
                return nil
            }
            return doc.at_xpath("//ROOT/\(storeName.uppercased())")
    }

```

and call it 

```
if let doc = XML(xml: storeConfig, encoding: String.Encoding.utf8) {
            let storeName = "BestBuy"
            print(getSite("BestBuy")?.toXML)
           
        }
```

**Comment by tid-kijyun** [comment]
I can't reproduce this error. 😢 
It seems there is a problem with the conversion of the `Data` from `NSData`.
I'll investigate this issue this weekend. 

Workaround: Please use `String` for now.

```
class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.

        guard let filePath = Bundle(for:self.classForCoder).path(forResource: "example", ofType:"xml") else {
            return
        }

        let xml = try! NSString(contentsOfFile: filePath, encoding: String.Encoding.utf8.rawValue)
        UserDefaults.standard.set(xml, forKey: "storeConfig")
        guard let storeConfig = UserDefaults.standard.string(forKey: "storeConfig") else {
            return
        }

        if let doc = XML(xml: storeConfig, encoding: String.Encoding.utf8) {
            let storeName = "BestBuy"
            print(getSite("BestBuy")?.toXML)
            let current = doc.xpath("//ROOT/*").map({ $0 })
            for c in current {
                let siteMatches = c.xpath("./MATCHES/*").map({ $0 })
                for siteMatch in siteMatches {
                    //print(siteMatch.toXML)
                }
            }
        }
    }

    func getSite(_ storeName:String, pageEncoding:String.Encoding = .utf8) -> XMLElement? {
        guard let storeConfig = UserDefaults.standard.string(forKey: "storeConfig") else {
            return nil
        }
        guard let doc = Kanna.XML(xml: storeConfig, encoding: pageEncoding) else {
            return nil
        }
        return doc.at_xpath("//ROOT/\(storeName.uppercased())")
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }   
}
```

**Comment by Arti3DPlayer** [comment]
thanks a lot

**Comment by Arti3DPlayer** [comment]
Sorry, but: 

```UserDefaults.standard.set(String(data: originalData, encoding: .utf8), forKey: "storeConfig")```

```func getSite(_ storeName:String, pageEncoding:String.Encoding = .utf8) -> XMLElement? {
        guard let storeConfig = UserDefaults.standard.string(forKey: "storeConfig") else {
            return nil
        }
        
        guard let doc = Kanna.XML(xml: storeConfig, encoding: pageEncoding) else {
            return nil
        }
        
        return doc.at_xpath("//ROOT/\(storeName.uppercased())")
    }```

return nothing too

**Comment by Arti3DPlayer** [comment]
```let storeConfig = UserDefaults.standard.string(forKey: "storeConfig"``` returns normal string

**Comment by tid-kijyun** [comment]
Sorry for my late reply.
I think that this issue was solved with the new release(v2.2.0).

**Comment by Arti3DPlayer** [comment]
Thanks:) what was the issue ?

**Comment by tid-kijyun** [comment]
This problem occurs when the HTMLDocument destroys.

Please refer to https://github.com/tid-kijyun/Kanna/issues/115#issuecomment-255394188 .

**Comment by tid-kijyun** [comment]
Please let me know if using the new version does not solve the problem.

Thanks
