### ISSUE TITLE
no such module libxml2

### ISSUE THREAD

**Issue by miracle0930** [tid-kijyun/Kanna#114]
### Description:

what does "and paste them into your [Modulename]-Bridging-Header.h

"mean? could you please explain?

### Installation method:
- [ ] Carthage
- [ ] CocoaPods(1.1.0 or later)
- [ ] CocoaPods(older)
- [x] Manually

### Library version:
- [ ] v2.0.0
- [ ] v1.1.1
- [ ] v1.0.6
- [ ] v1.0.2
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [ ] 8.0 (Swift 3.0) 
- [ ] 8.0 (Swift 2.3)
- [x] 7.3.1
- [ ] other: (Please fill in the version you are using.)

**Comment by tid-kijyun** [comment]
Which version do you use?
Please use version v1.1.1 if you are using Xcode 7.3.1.

https://github.com/tid-kijyun/Kanna/releases/tag/1.1.1

**Comment by miracle0930** [comment]
I've solved the problem, thanks for your help!
