### ISSUE TITLE
Crash in libxmlHTMLNode.swift, line 41, libxmlHTMLNode.toHTML.getter

### ISSUE THREAD

**Issue by davetroy** [tid-kijyun/Kanna#116]
### Description:

Attempting to use Kanna to extract HTML from arbitrary HTML doc (email bodies). Am getting this crash occasionally (EXC_BAD_ACCESS KERN_INVALID_ADDRESS); appears to be a memory issue with regards to libXML <> Kanna. Possibly there is some other valid error condition but in no case should it cause a crash. This appears to have emerged fairly recently; saw it with 1.1.0 and then installed 1.1.1 and am still seeing it.

```
        // doc is a Kanna HTMLDocument, content is a String
        var innerHead = doc?.head?.innerHTML ?? ""
        let style = doc?.xpath("head//style")

        let innerBody = doc?.body?.innerHTML ?? content // <- *Crash is Here*
```
### Installation method:
- [x] CocoaPods(1.1.0 or later)
### Library version:
- [x] v1.1.1
### Xcode version:
- [x] 8.1 (Swift 2.3)

**Comment by davetroy** [comment]
I believe we have fixed this in our code; the issue seems to be caused by referring to an HTMLDocument inside a class method, which doesn't seem to retain the document properly.

**Comment by tid-kijyun** [comment]
Closed because it is a problem in the old version.
Feel free to repost if the issue is not resolved.
