### ISSUE TITLE
XPath error from CSS conversion with attribute selector

### ISSUE THREAD

**Issue by th1rt3en** [tid-kijyun/Kanna#120]
### Description:
Consider the following expression 
```
"#mainTopicTable tr[id^=\"Thread_\"]"
```
Will raise 
```
XPath error : Invalid expression
//*[@id = 'mainTopicTable']//tr[@id*="Thread_"]
```
at the position `*=`

### Installation method:
- [x] Carthage
- [ ] CocoaPods(1.1.0 or later)
- [ ] CocoaPods(older)
- [ ] Manually

### Library version:
- [ ] v2.0.0
- [ ] v1.1.1
- [ ] v1.0.6
- [ ] v1.0.2
- [x] other: 2.0.3

### Xcode version:
- [x] 8.0 (Swift 3.0) 
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

**Comment by tid-kijyun** [comment]
Please change \" to ' for now.

```
"#mainTopicTable tr[id^='Thread_']"
```

I will fix this issue in the next version.
