### ISSUE TITLE
macOS deployment target is set to 10.12 when built via Carthage

### ISSUE THREAD

**Issue by inket** [tid-kijyun/Kanna#124]
### Description:
Installed through Carthage, the framework's `MACOSX_DEPLOYMENT_TARGET` is 10.12 (Sierra). Is this intended?

This is the responsible commit: https://github.com/tid-kijyun/Kanna/commit/229680f12f26cf88300db95532440bbbf1db6e0c

**Comment by tid-kijyun** [comment]
I just fixed this issue.  [v2.1.1.](https://github.com/tid-kijyun/Kanna/releases/tag/2.1.1)

**Comment by inket** [comment]
Thank you!
