### ISSUE TITLE
using Swift Package Manager build failed

### ISSUE THREAD

**Issue by RoshanDev** [tid-kijyun/Kanna#125]
### Description:
swift build failed
![failed](https://cloud.githubusercontent.com/assets/4354429/21022238/dedd3958-bdb6-11e6-8bb1-a08e56a16f05.png)

### Installation method:
- [ ] Carthage
- [ ] CocoaPods(1.1.0 or later)
- [ ] CocoaPods(older)
- [ ] Manually
- [x] Swift Package Manager

### Library version:
- [x] v2.1.1
- [ ] v2.0.0
- [ ] v1.1.1
- [ ] v1.0.6
- [ ] v1.0.2
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 8.1 (Swift 3.0.1) 
- [ ] 8.0 (Swift 3.0) 
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

**Comment by tid-kijyun** [comment]
Hi @RoshanDev 

You need to install the libxml2 to build with Swift Package Manager.
Please see the log message.

```
note: you may be able to install libxml-2.0 using your system-packager:

    brew install libxml2

```

Thanks

**Comment by RoshanDev** [comment]
Hi, I have installed libxml2, here is the message
![libxml](https://cloud.githubusercontent.com/assets/4354429/21035325/2e21fd18-bdf9-11e6-84d5-1173561b23cc.png)

**Comment by RoshanDev** [comment]
Here is the [demo project](https://github.com/RoshanDev/HelloKanna.git)

**Comment by tid-kijyun** [comment]
Please try it.

`brew link --force libxml2`

**Comment by tid-kijyun** [comment]
[FYI] When the build is successful, it is displayed as follows:
![screen shot 2016-12-09 at 15 36 08](https://cloud.githubusercontent.com/assets/1665104/21040317/800b782e-be27-11e6-8e15-979423581a39.png)

**Comment by RoshanDev** [comment]
Thank you very much! 
The build is successful😁
![success](https://cloud.githubusercontent.com/assets/4354429/21041433/ee8332f8-be25-11e6-9e85-afc9a06d8686.png)

**Comment by tid-kijyun** [comment]
I just added this point to the Readme.
Thanks 👍

**Comment by RoshanDev** [comment]
It was my pleasure😁
