### ISSUE TITLE
Getting build error after adding Kanna to a Swift 3.0 project

### ISSUE THREAD

**Issue by mkostersitz** [tid-kijyun/Kanna#126]
### Description:
I get these build errors after adding Kanna using CocoaPods (1.1.1)
/..../Kanna.swift:64:12: Argument labels '(xml:, encoding:, option:)' do not match any available overloads
this repeats for all of the XML and HTML functions in Kanna.swift
### Installation method:
- [ ] Carthage
- [X] CocoaPods(1.1.0 or later) 1.2.0 beta 1
- [ ] CocoaPods(older)
- [ ] Manually

### Library version:
- [ ] v2.0.0
- [ ] v1.1.1
- [ ] v1.0.6
- [ ] v1.0.2
- [X] other: (Please fill in the version you are using.) 2.1.1

### Xcode version:
- [ ] 8.0 (Swift 3.0) 
- [ ] 8.0 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

**Comment by tid-kijyun** [comment]
Please try clean build. `Cmd + Shift + K`, `Cmd + B`

**Comment by mkostersitz** [comment]
Unfortunately that did not help :(

**Comment by tid-kijyun** [comment]
Please let me ask a few questions.

1. Did an error occur due to library version upgrade from 2.0.x? 
1. Does the same error occur in a new project?

Thanks

**Comment by mkostersitz** [comment]
No errors only 600+ warnings about the missing files
Yes same in a brand new project. Maybe something to do with the basic CocoaPods setup?

**Comment by tid-kijyun** [comment]
Would you show me the contents of Podfile?

FYI: Here is my brand new project Podfile.
```
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SampleApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Kanna', '~> 2.1.0'
  # Pods for SampleApp

  target 'SampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

**Comment by mkostersitz** [comment]
Sure here is the one from the blank app I tried with

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SampleApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Kanna','~>2.1.1'
  # Pods for SampleApp

  target 'SampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SampleAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

**Comment by tid-kijyun** [comment]
It seems that there is no problem...
Would you upload the brand new project to github?

**Comment by mkostersitz** [comment]
I took an Xcode update for 10.2 Beta and now the issue disappeared :(

Mike

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
[HxS - 14986 - 16.0.7628.1454]

**Comment by tid-kijyun** [comment]
Well, Has your problem been solved? Please close this issue if there is no problem.

Thanks

**Comment by mkostersitz** [comment]
Thanks for the prompt help seems to have been an issue with my Xcode installation.
