### ISSUE TITLE
Get only node content without other elements

### ISSUE THREAD

**Issue by voynovia** [tid-kijyun/Kanna#127]
### Description:

```
<div class="speciality">
   <div class="numbers">Another Text</div>
   Some Text
</div>
```

What css expression should I use to only get the div content ("Some Text") without his child elements (div. numbers)

### Installation method:
- [ ] CocoaPods(1.1.0 or later)

### Library version:
- [ ] v2.1.1

### Xcode version:
- [ ] 8.1 (Swift 3)

**Comment by tid-kijyun** [comment]
Probably, It can not be done with CSS expression.
Please use the xpath expression. 

```
if let doc = HTML(html: html, encoding: .utf8) {
    let x = "string(//div[@class='speciality']/text())"
    let item = doc.xpath(x)
    print(item.string!)
}
```

**Comment by voynovia** [comment]
thanks
