### ISSUE TITLE
iterating through html

### ISSUE THREAD

**Issue by jky5036** [tid-kijyun/Kanna#128]
### Installation method:
- [ ] Carthage
- [x ] CocoaPods(1.1.0 or later)
- [ ] Swift Package Manager
- [ ] Manually
- [ ] other: ()

### Library version:
- [ ] v2.1.1
- [ x] other: ()

### Xcode version:
- [ ] 8.1 (Swift 3) 
- [ ] 8.1 (Swift 2.3)
- [ x] 7.3.1
- [ ] other: ()
So how would I be able to iterate through individual subnodes of a div? Say this html has 20 "articles". When I run this code, I am able to succesfully iterate 20 times, but I am only getting the first element "img" repeated 20 times instead of iterating through them. Thoughts?

`func populateInitialArticles(inputHTML: NSString){
       
        if let document = Kanna.HTML(html: inputHTML as String, encoding: NSUTF8StringEncoding){
           
            let articles = document.xpath("//main[contains(@class,'Main Main--blog-list')]//article")
        
            for article in articles{
            
                let new = article.at_xpath("//div//a//img//@data-src")
                print(new?.text)
    }
            
        }
        
    }
`

**Comment by tid-kijyun** [comment]
Please correct `"//div//a//img//@data-src"` to `"/div//a//img//@data-src"` or `"div//a//img//@data-src"`.

**Comment by jky5036** [comment]
Ahh thank you, still new to XPATH. PS: Love this library!
