### ISSUE TITLE
How to use Kanna in Xcode 8.2 : No such module "Kanna"

### ISSUE THREAD

**Issue by belladiallo** [tid-kijyun/Kanna#129]
### Description:
Hello Tid,
I was usisng you old swift-HTML-Parser and now i want to migrate to xcode 8.2.
By following http://tid-kijyun.github.io/Kanna/ , I used cocoaPods

this is my podfile content:
![screen shot 2016-12-22 at 10 50 11 am](https://cloud.githubusercontent.com/assets/6549384/21431183/4de9e030-c834-11e6-9c48-cd2602504dad.png)

In the terminale I did:

![image](https://cloud.githubusercontent.com/assets/6549384/21430945/5eb483b2-c833-11e6-8f0b-7b2edc6cfbe8.png)

The folder of my xcode projet TutorialKanna:
![screen shot 2016-12-22 at 10 51 31 am](https://cloud.githubusercontent.com/assets/6549384/21431289/a779ed8e-c834-11e6-948d-8575a8d059b1.png)

More :
![screen shot 2016-12-22 at 10 52 00 am](https://cloud.githubusercontent.com/assets/6549384/21431363/eb7d80d6-c834-11e6-9118-e00030c75b7b.png)

Question:
Am I missing something ?
How can I fixed it plesae ?
Thanks

![image](https://cloud.githubusercontent.com/assets/6549384/21431631/fed4553c-c835-11e6-9c99-d6df7e2e150b.png)

### Installation method:
- [ ] CocoaPods(1.1.0 or later)

### Library version:
- [ ] v2.1.1

### Xcode version:
- [ ] 8.2 (Swift 3)

**Comment by miws** [comment]
need open tutorialKanna.xcworkspace.

**Comment by jasef** [comment]
You've probably already solved this by now, but for any who come here... your import statement must be `import Kanna`, not `import kanna`

**Comment by raytso** [comment]
I can confirm that it works on 8.2.1

**Comment by tid-kijyun** [comment]
It seems that this has already been resolved.
Please feel free to reopen if it is not resolved.
