### ISSUE TITLE
Could not build Objective-C module 'libxml2'

### ISSUE THREAD

**Issue by mhillebrand** [tid-kijyun/Kanna#133]
### Description:

I ran both the `brew install libxml2` and `brew link --force libxml2` commands successfully, I added the header search path `$(SDKROOT)/usr/include/libxml2`, and I still get these build errors:

`/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.2.sdk/usr/include/libxml2/libxml/HTMLtree.h:15:10: 'libxml/xmlversion.h' file not found`

`Could not build Objective-C module 'libxml2'`

### Installation method:
- [x] Carthage
- [ ] CocoaPods(1.1.0 or later)
- [ ] Swift Package Manager
- [ ] Manually
- [ ] other: ()

### Library version:
- [x] v2.1.1
- [ ] other: ()

### Xcode version:
- [x] 8.2.1 (Swift 3.0.2) 
- [ ] 8.1 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: ()

**Comment by mhillebrand** [comment]
Any advice would be great!

**Comment by tid-kijyun** [comment]
Hi @mhillebrand 

1. Are you using the latest Carthage?
2. Does this problem also occur in brand new projects?

> I ran both the `brew install libxml2` and `brew link --force libxml2`

Note: You don't need to execute these commands when using Carthage.

**Comment by mhillebrand** [comment]
Yes, I created a brand new iOS project and got the following build error:

```
CompileSwift normal x86_64 /Users/mhillebrand/temp/Kanta/Kanta/ViewController.swift
    cd /Users/mhillebrand/temp/Kanta
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c -primary-file /Users/mhillebrand/temp/Kanta/Kanta/ViewController.swift /Users/mhillebrand/temp/Kanta/Kanta/AppDelegate.swift -target x86_64-apple-ios10.2 -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.2.sdk -I /Users/mhillebrand/Library/Developer/Xcode/DerivedData/Kanta-beoisfufeqlvoycjfezttmpgndjd/Build/Products/Debug-iphonesimulator -F /Users/mhillebrand/Library/Developer/Xcode/DerivedData/Kanta-beoisfufeqlvoycjfezttmpgndjd/Build/Products/Debug-iphonesimulator -F /Users/mhillebrand/temp/Kanta/Carthage/Build/iOS -enable-testing -g -module-cache-path /Users/mhillebrand/Library/Developer/Xcode/DerivedData/ModuleCache -D DEBUG -serialize-debugging-options -Xcc -I/Users/mhillebrand/Library/Developer/Xcode/DerivedData/Kanta-beoisfufeqlvoycjfezttmpgndjd/Build/Intermediates/Kanta.build/Debug-iphonesimulator/Kanta.build/swift-overrides.hmap -Xcc -iquote -Xcc /Users/mhillebrand/Library/Developer/Xcode/DerivedData/Kanta-beoisfufeqlvoycjfezttmpgndjd/Build/Intermediates/Kanta.build/Debug-iphonesimulator/Kanta.build/Kanta-generated-files.hmap -Xcc -I/Users/mhillebrand/Library/Developer/Xcode/DerivedData/Kanta-beoisfufeqlvoycjfezttmpgndjd/Build/Intermediates/Kanta.build/Debug-iphonesimulator/Kanta.build/Kanta-own-target-headers.hmap -Xcc -I/Users/mhillebrand/Library/Developer/Xcode/DerivedData/Kanta-beoisfufeqlvoycjfezttmpgndjd/Build/Intermediates/Kanta.build/Debug-iphonesimulator/Kanta.build/Kanta-all-target-headers.hmap -Xcc -iquote -Xcc /Users/mhillebrand/Library/Developer/Xcode/DerivedData/Kanta-beoisfufeqlvoycjfezttmpgndjd/Build/Intermediates/Kanta.build/Debug-iphonesimulator/Kanta.build/Kanta-project-headers.hmap -Xcc -I/Users/mhillebrand/Library/Developer/Xcode/DerivedData/Kanta-beoisfufeqlvoycjfezttmpgndjd/Build/Products/Debug-iphonesimulator/include -Xcc -I/Users/mhillebrand/Library/Developer/Xcode/DerivedData/Kanta-beoisfufeqlvoycjfezttmpgndjd/Build/Intermediates/Kanta.build/Debug-iphonesimulator/Kanta.build/DerivedSources/x86_64 -Xcc -I/Users/mhillebrand/Library/Developer/Xcode/DerivedData/Kanta-beoisfufeqlvoycjfezttmpgndjd/Build/Intermediates/Kanta.build/Debug-iphonesimulator/Kanta.build/DerivedSources -Xcc -DDEBUG=1 -Xcc -working-directory/Users/mhillebrand/temp/Kanta -emit-module-doc-path /Users/mhillebrand/Library/Developer/Xcode/DerivedData/Kanta-beoisfufeqlvoycjfezttmpgndjd/Build/Intermediates/Kanta.build/Debug-iphonesimulator/Kanta.build/Objects-normal/x86_64/ViewController~partial.swiftdoc -Onone -module-name Kanta -emit-module-path /Users/mhillebrand/Library/Developer/Xcode/DerivedData/Kanta-beoisfufeqlvoycjfezttmpgndjd/Build/Intermediates/Kanta.build/Debug-iphonesimulator/Kanta.build/Objects-normal/x86_64/ViewController~partial.swiftmodule -serialize-diagnostics-path /Users/mhillebrand/Library/Developer/Xcode/DerivedData/Kanta-beoisfufeqlvoycjfezttmpgndjd/Build/Intermediates/Kanta.build/Debug-iphonesimulator/Kanta.build/Objects-normal/x86_64/ViewController.dia -emit-dependencies-path /Users/mhillebrand/Library/Developer/Xcode/DerivedData/Kanta-beoisfufeqlvoycjfezttmpgndjd/Build/Intermediates/Kanta.build/Debug-iphonesimulator/Kanta.build/Objects-normal/x86_64/ViewController.d -emit-reference-dependencies-path /Users/mhillebrand/Library/Developer/Xcode/DerivedData/Kanta-beoisfufeqlvoycjfezttmpgndjd/Build/Intermediates/Kanta.build/Debug-iphonesimulator/Kanta.build/Objects-normal/x86_64/ViewController.swiftdeps -o /Users/mhillebrand/Library/Developer/Xcode/DerivedData/Kanta-beoisfufeqlvoycjfezttmpgndjd/Build/Intermediates/Kanta.build/Debug-iphonesimulator/Kanta.build/Objects-normal/x86_64/ViewController.o

<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "libxml2-kanna.h"
        ^
/Users/mhillebrand/temp/Kanta/Carthage/Checkouts/Kanna/Modules/libxml2-kanna.h:1:9: note: in file included from /Users/mhillebrand/temp/Kanta/Carthage/Checkouts/Kanna/Modules/libxml2-kanna.h:1:
#import <libxml2/libxml/HTMLtree.h>
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.2.sdk/usr/include/libxml2/libxml/HTMLtree.h:15:10: error: 'libxml/xmlversion.h' file not found
#include <libxml/xmlversion.h>
         ^
<unknown>:0: error: could not build Objective-C module 'libxml2'```

**Comment by mhillebrand** [comment]
Have you got any advice? My team and I would *really* like to move away from Cocoa Pods, and this is the last pod in our project. Everything else is installed via Carthage. Thanks!

**Comment by tid-kijyun** [comment]
Hi @mhillebrand 

Does the same error occur in this sample project? 

https://github.com/tid-kijyun/SampleKanna

**Comment by mhillebrand** [comment]
@tid-kijyun, I'm getting a different error with that sample project: 

<img width="1334" alt="screenshot 2017-02-07 10 23 42" src="https://cloud.githubusercontent.com/assets/286198/22705239/9df17718-ed1f-11e6-879c-4fcc61dc7326.png">

**Comment by mhillebrand** [comment]
ARGH! I tried installing manually and got this error:

![screenshot 2017-02-07 14 25 39](https://cloud.githubusercontent.com/assets/286198/22714442/5cd93334-ed41-11e6-94b7-c2c87417d607.png)

I do not want to use Cocoa Pods, but that seems to be the only way to use Kanna?!?!? Please advise. Thanks.

**Comment by tid-kijyun** [comment]
Please check the header search pass again in your brand new project.

![screen shot 2017-02-08 at 10 32 30](https://cloud.githubusercontent.com/assets/1665104/22719689/019bb8d0-edea-11e6-8af1-2e0a242b1ae9.png)

**Comment by mhillebrand** [comment]
It does not work.

![screenshot 2017-02-07 17 53 55](https://cloud.githubusercontent.com/assets/286198/22720243/74732532-ed5e-11e6-9bcb-2013c3cd0cc5.png)

**Comment by mhillebrand** [comment]
Here is a new project (.zip file) for you to try it on your own. 

[K.zip](https://github.com/tid-kijyun/Kanna/files/759513/K.zip)

**Comment by tid-kijyun** [comment]
Please upload a new project containing carthage build.

**Comment by tid-kijyun** [comment]
I added the manual installation for Swift 3.x to README.md.

https://github.com/tid-kijyun/Kanna/blob/master/README.md#manual-installation

**Comment by MingLoan** [comment]
So no fixes for Carthage in the future?

**Comment by tid-kijyun** [comment]
I cannot reproduce this error in my environment.
I need a project that contains errors to investigate the cause.

@MingLoan 
Have you also encountered the same error?

**Comment by mhillebrand** [comment]
Here you go. Here is a brand new project that simply cannot integrate Kanna via Carthage. It's name is Karthage:

[Karthage.zip](https://github.com/tid-kijyun/Kanna/files/759753/Karthage.zip)

**Comment by tid-kijyun** [comment]
The `header search path` seems to be blank...

![screen shot 2017-02-08 at 14 00 44](https://cloud.githubusercontent.com/assets/1665104/22724108/5a65b6ce-ee07-11e6-8351-5e31fd652ce3.png)

**Comment by mhillebrand** [comment]
@tid-kijyun I'm sorry, but your new manual installation instructions don't work either. There are 37 build errors:

<img width="1254" alt="screenshot 2017-02-07 21 08 25" src="https://cloud.githubusercontent.com/assets/286198/22724207/a8cf49c6-ed79-11e6-9bf8-d30861598ad2.png">

[K.zip](https://github.com/tid-kijyun/Kanna/files/759768/K.zip)

**Comment by mhillebrand** [comment]
`Header Search Paths` is blank in the Carthage project (Karthage.zip), but it's set in the Manual Installation project (K.zip). Are you confusing the two? Neither of them works.

<img width="1184" alt="screenshot 2017-02-07 21 13 42" src="https://cloud.githubusercontent.com/assets/286198/22724362/69cfa828-ed7a-11e6-8ecb-8bd4f826610a.png">

**Comment by tid-kijyun** [comment]
Advice for manual instalation (K):
Please remove following include sentense in bridging header file.

```
#import <libxml/HTMLtree.h>
#import <libxml/xpath.h>
#import <libxml/xpathInternals.h>
```

Advice for carthage instalation (Karthage):
1. Please add `$(SDKROOT)/usr/include/libxml2` to Header Search Paths.
2. Please run carthage update again.
```
carthage update --platform iOS
```

**Comment by mhillebrand** [comment]
WOO HOO! It now works via Carthage. Thank you.

<img width="1199" alt="screenshot 2017-02-07 21 36 20" src="https://cloud.githubusercontent.com/assets/286198/22724805/8f32635a-ed7d-11e6-9540-a69e929487b6.png">
