### ISSUE TITLE
pod lib lint fails (no such module 'libxml2')

### ISSUE THREAD

**Issue by rpitting** [tid-kijyun/Kanna#135]
### Description:

It seems that the approach to make the library work with CocoaPods, libxml and Swift does not work.

When you do `pod lib lint`, you get the following error:

```    
- ERROR | xcodebuild:  .../Kanna/Sources/Kanna/CSS.swift:30:8: error: no such module 'libxml2'
```

### Installation method:
- [ ] Carthage
- [X] CocoaPods(1.1.0 or later)
- [ ] Swift Package Manager
- [ ] Manually
- [ ] other: ()

### Library version:
- [X] v2.1.1
- [ ] other: ()

### Xcode version:
- [X] 8.1 (Swift 3) 
- [ ] 8.1 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: ()

**Comment by sinss** [comment]
Maybe you should add these  "$(SRCROOT)/Library", "$(SRCROOT)/Library" to "Header Search Paths" in Build settings.
This is what I worked.

**Comment by tid-kijyun** [comment]
Please try `pod spec lint`. This should succeed.

It seems that the `pod lib lint` will fail on projects using modulemap. (Including Kanna)
I think this problem is a problem of CocoaPods.

**Comment by rpitting** [comment]
Strange indeed. Are you however able to push updates of your library to the official specs dir?

I think `pod repo push` always includes a `pod lib lint`, and that always failed when I tried to publish my (private) pod.

**Comment by tid-kijyun** [comment]
To push updates to the official specs dir, I use `pod trunk push`. 
It seems that it is internally using `pod spec lint`.

Do you want to include this library in your private repository?

**Comment by sinss** [comment]
Oh , It’s my fault , I’m trying to build my own pod , so I’ll remove it from the official specs dir

**Comment by tid-kijyun** [comment]
This problem has been resolved.
Feel free to repost if the issue is not resolved.
