### ISSUE TITLE
When release build with iOS9, it will be crush

### ISSUE THREAD

**Issue by bati668** [tid-kijyun/Kanna#136]
### Description:

① When release build with iOS9, it will be crushed. debug build is ok
![2017-03-01 12 48 39](https://cloud.githubusercontent.com/assets/11172948/23445271/a2ab562e-fe7d-11e6-8ead-f2cb45ff6345.png)

My code is here
![2017-03-01 12 51 37](https://cloud.githubusercontent.com/assets/11172948/23445305/d813652c-fe7d-11e6-8771-63eed3c9e8f9.png)

### Installation method:
- [ ] Carthage

### Library version:
- [ ] v2.1.1

### Xcode version:
- [ ] 8.1 (Swift 3)

**Comment by tid-kijyun** [comment]
This problem will be fixed in the next version.

#### Workaround
The 6 and 7 lines are rewritten like this:

```
let css = p.css("img")
```

Probably this crash does not occur after rewriting.

**Comment by tid-kijyun** [comment]
This issue was solved with the new release(v2.2.0).
