### ISSUE TITLE
How to handle duplicate id

### ISSUE THREAD

**Issue by mwcs01** [tid-kijyun/Kanna#14]
Getting this error.
:76: element div: validity error : ID header-print already defined 
<div id="header-print">

How can I get it to continue past this? And no I can not remove the duplicate tag.

**Comment by tid-kijyun** [comment]
If you'd like to avoid an error output, do as follows.
```
var err : NSError?
let option = CInt(HTML_PARSE_NOERROR.value | HTML_PARSE_RECOVER.value)
var parser     = HTMLParser(html: html, encoding: NSUTF8StringEncoding, option: option, error: &err)
```
similar #10
