### ISSUE TITLE
Error with typealias to RegularExpression

### ISSUE THREAD

**Issue by yura-voevodin** [tid-kijyun/Kanna#142]
### Description:
Failed to build project on **Ubuntu 16.04**, getting this error:
`
"Kanna/CSS.swift:35:34: error: use of undeclared type 'RegularExpression'
typealias AKRegularExpression  = RegularExpression
                                 ^~~~~~~~~~~~~~~~~"
`
### Installation method:
- [ ] Carthage
- [ ] CocoaPods(1.1.0 or later)
- [x] Swift Package Manager
- [ ] Manually
- [ ] other: ()

### Library version:
- [x] v2.2.0
- [ ] v2.1.1
- [ ] other: ()

### Xcode version:
- [x] 8.3 (Swift 3.1) 
- [ ] 8.1 (Swift 3) 
- [ ] 8.1 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: ()

**Comment by svanimpe** [comment]
I have the exact same error :( I am developing on macOS but deploying to Bluemix (Ubuntu 14.04 + Swift 3.1).

**Comment by tid-kijyun** [comment]
I've just fixed this issue. Please use v2.1.1.

**Comment by yura-voevodin** [comment]
It works, thank you! 👍
