### ISSUE TITLE
How to install it in Swift project?

### ISSUE THREAD

**Issue by lmcmz** [tid-kijyun/Kanna#15]
As I know, Using _Bridging_Header.h just is necessary in Object-C project.
I tried to put the HTMLParsing.swift and HTMLNode.swift files to my Swift project but it didn't work.
:(
Thanks your nice project, help me a lot.
XD

**Comment by tid-kijyun** [comment]
Well, please use it. :D
https://github.com/zootreeves/Objective-C-HMTL-Parser
