### ISSUE TITLE
convert <br> as \r\n

### ISSUE THREAD

**Issue by foolbear** [tid-kijyun/Kanna#150]
### Description:

When I parser url "http://m.263xs.com/wapbook-509779-34263688/" to get chapter content using:
guard let content = body.xpath("//*[@id=\"fiction_container\"]/p").first?.content else { return nil }

original html:
`<p>&nbsp;&nbsp;&nbsp;&nbsp;高人，这个人绝对是高人！中年男子的心中不由得燃起了希望来！都说高手在民间，这话一点儿也不假，至少中年男子就知道，民间有一位奇人，所以对于瘦高男子的身份也没有多大的怀疑，毕竟不是什么人都知道他的问题的，他的问题，连他的女儿都不知道，只有他的司机知道。<br /><br />&nbsp;&nbsp;&nbsp;&nbsp;瘦高男子这回却是不再说这些了，只是对中年男子点了点头，道：“老兄要注意保养身体，不要太累了，以你的年纪，在家休养休养，对延年益寿有好处。”<br /><br />&nbsp;&nbsp;&nbsp;&nbsp;“敢问这位神医，我的问题，是否有治疗的方案？”中年男子见这位神医不再说他的病了只是让他多休息，更是不疑有它，虽然多年的商业经验也提醒他，世界上哪有那么多巧合？<br /><br />&nbsp;&nbsp;&nbsp;&nbsp;但是关心则乱，想到困扰自己多年的老毛病可能治愈，他真是十分的激动！毕竟，他真的不能休息，休息了，企业谁去管理？<br />...</p>`

function result:
"    高人，这个人绝对是高人！中年男子的心中不由得燃起了希望来！都说高手在民间，这话一点儿也不假，至少中年男子就知道，民间有一位奇人，所以对于瘦高男子的身份也没有多大的怀疑，毕竟不是什么人都知道他的问题的，他的问题，连他的女儿都不知道，只有他的司机知道。    瘦高男子这回却是不再说这些了，只是对中年男子点了点头，道：“老兄要注意保养身体，不要太累了，以你的年纪，在家休养休养，对延年益寿有好处。”    “敢问这位神医，我的问题，是否有治疗的方案？”中年男子见这位神医不再说他的病了只是让他多休息，更是不疑有它，虽然多年的商业经验也提醒他，世界上哪有那么多巧合？    但是关心则乱，想到困扰自己多年的老毛病可能治愈，他真是十分的激动！毕竟，他真的不能休息，休息了，企业谁去管理？	...

I found `&nbsp;` -> " "(blank), but `<br/>\<br />\<br>` disappear, how can i convert them as \r\n or \n??

### Installation method:
- [ ] Carthage
- [ ] CocoaPods(1.1.0 or later)
- [ ] Swift Package Manager
- [*] Manually
- [ ] other: ()

### Library version:
- [*] v2.1.1
- [ ] other: ()

### Xcode version:
- [*] 8.1 (Swift 3) 
- [ ] 8.1 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: ()

**Comment by foolbear** [comment]
@tid-kijyun

**Comment by tid-kijyun** [comment]
Please convert `<br/> <br />` to `\r\n` before parsing.

```
let html2 = html.replacingOccurrences(of: "<br>|<br />", with: "\r\n", options: .regularExpression, range: nil)
```
