### ISSUE TITLE
Couldn't process HTML Tags

### ISSUE THREAD

**Issue by aatish-rajkarnikar** [tid-kijyun/Kanna#152]
## Here is the html rendered on web:
![photo](https://user-images.githubusercontent.com/19183428/27673551-065c82aa-5cc1-11e7-8671-e2cc1a4ac96e.jpg)

## And here is the same html rendered on app using Kanna.
![photo-2](https://user-images.githubusercontent.com/19183428/27673562-11f057e0-5cc1-11e7-96f6-f22e2ec8a2db.jpg)

## I am using the following code to process HTML
`guard let desc = HTML(html: value, encoding: .utf8) else{return}`
`self.bodyLabel.text = desc.text`

### Installation method:
- [x] Carthage
- [ ] CocoaPods(1.1.0 or later)
- [ ] Swift Package Manager
- [ ] Manually
- [ ] other: ()

### Library version:
- [x] v2.1.1
- [ ] other: ()

### Xcode version:
- [x] 8.1 (Swift 3) 
- [ ] 8.1 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: ()

**Comment by tid-kijyun** [comment]
Kanna is an HTML **parser**.
It is used for scraping etc.

Text styling is not supported by this library.
