### ISSUE TITLE
Xcode 9

### ISSUE THREAD

**Issue by MakiCodes** [tid-kijyun/Kanna#158]
Hi there,

I can't import Kanna into my Xcode 9 project.
I used the branch "feature/v4.0.0" in my podfile and installed it with the terminal.
In my Xcode 9 project it says "Cannot load underlying module for 'Kanna'" after importing it.

Has anybody else this problem, or can somebody help me please?

Thanks!

### Installation method:
- [ ] CocoaPods(1.1.0 or later)

### Library version:
- [ ] v2.1.1
- [ ] other: ()

### Xcode version:
9

**Comment by tid-kijyun** [comment]
Please try clean and build.

`cmd + shift + k` > `cmd + b`

**Comment by MakiCodes** [comment]
It works! Thank you!

**Comment by t2ac32** [comment]
@MakiCodes  could you please explain how to install the Feature/v4.0.0 versión from cocoa pods :) 
thanks on advance.
