### ISSUE TITLE
Xcode 9.1 - Characters is deprecated

### ISSUE THREAD

**Issue by saldous** [tid-kijyun/Kanna#163]
### Description:
7 new warnings in Xcode 9.1, all in CSS.swift:

> 'characters' is deprecated: Please use String or Substring directly

### Installation method:
- [ ] Carthage
- [X] CocoaPods(1.1.0 or later)
- [ ] Swift Package Manager
- [ ] Manually
- [ ] other: ()

### Library version:
- [X] v2.1.1
- [ ] other: ()

### Xcode version:
- [X ] 9.1 (Swift 4) 
- [ ] 8.1 (Swift 3) 
- [ ] 8.1 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: ()

**Comment by ycaxgjd** [comment]
Delete all "characters."😏

**Comment by tid-kijyun** [comment]
Please try version [4.0.0](https://github.com/tid-kijyun/Kanna/releases/tag/4.0.0).
