### ISSUE TITLE
carthage libxml2 error

### ISSUE THREAD

**Issue by medisean** [tid-kijyun/Kanna#168]
### Description:

Copy carthage folder from other developer computer, missing required module libxml2.
<img width="348" alt="2017-11-14 2 07 42" src="https://user-images.githubusercontent.com/6093631/32765516-678d6686-c8d0-11e7-95fd-7fbaaf6d0277.png">

### Installation method:
- Carthage

### Library version:
- v2.1.1

### Xcode version:
- 9.1

**Comment by cliftonlabrum** [comment]
Any luck with this?

**Comment by Lorwy** [comment]
![image](https://user-images.githubusercontent.com/6788741/33062570-b7577ae8-ceda-11e7-9d4c-50e6e744dc87.png)
报错

**Comment by tid-kijyun** [comment]
Have you made the necessary settings?

> In the project settings add $(SDKROOT)/usr/include/libxml2 to the "header search paths" field.

**Comment by medisean** [comment]
Thanks.

**Comment by Lorwy** [comment]
Thanks,I've solved this problem
