### ISSUE TITLE
Tag is missing, Readme is ambiguous

### ISSUE THREAD

**Issue by afisdev** [tid-kijyun/Kanna#170]
### Description:
Tag 4.0.0 in master branch is missing.
Furthermore the Readme is linking to feature/4.0.0 but this is merged already.

### Installation method:
- [ ] Carthage
- [x ] CocoaPods(1.1.0 or later)
- [ ] Swift Package Manager
- [ ] Manually
- [ ] other: ()

### Library version:
- [ ] v2.1.1
- [x ] other: (4.0.0)

### Xcode version:
- [ ] 8.1 (Swift 3) 
- [ ] 8.1 (Swift 2.3)
- [ ] 7.3.1
- [ x] other: (9.1)

**Comment by tid-kijyun** [comment]
It was solved.
