### ISSUE TITLE
exit error 1

### ISSUE THREAD

**Issue by roma095** [tid-kijyun/Kanna#171]
### Description:

When i start project with emulators - all build ok. But if i use device or try to archive or test project, get this error:

himkiSchool.app/Frameworks/Kanna.framework'
/Users/jammer/Library/Developer/Xcode/DerivedData/himkiSchool-bioyyuyeaskaoebrlqwbuafvwjev/Build/Products/Debug-iphoneos/himkiSchool.app/Frameworks/Kanna.framework: unknown error -1=ffffffffffffffff

how can i solve it? I try to make clear project - the same problem. Xcode 9.01 and 9.1 try

### Installation method:
- [ ] Carthage
- [ X] CocoaPods(1.1.0 or later)
- [ ] Swift Package Manager
- [ ] Manually
- [ ] other: ()

### Library version:
- [X ] v2.1.1
- [ ] other: ()

### Xcode version:
- [ ] 8.1 (Swift 3) 
- [ ] 8.1 (Swift 2.3)
- [ ] 7.3.1
- [ X] other: (Swift 3.2, Swift 4.0)

![1212](https://user-images.githubusercontent.com/26276785/33475008-d42bf260-d68d-11e7-9fcb-47cab9b1b5cb.png)

**Comment by tid-kijyun** [comment]
Closed because it is a problem in the old version.
Feel free to repost if the issue is not resolved.
