### ISSUE TITLE
undeclared type 'TextCheckingResult'

### ISSUE THREAD

**Issue by heibear** [tid-kijyun/Kanna#173]
### Description:
On my Ubuntu build project, I get the following error:

Sources/Kanna/CSS.swift:34:34: error: use of undeclared type 'TextCheckingResult'
typealias AKTextCheckingResult = TextCheckingResult
                                 ^~~~~~~~~~~~~~~~~~

### Installation method:
 Swift Package Manager

### Library version:
- [ ] v2.1.1

### Xcode version:
- [ ] 9.1 (Swift 4)

**Comment by tid-kijyun** [comment]
@heibear 

For now Swift 4 should use the "feature/v4.0.0" or "master" branch.

**Comment by burf2000** [comment]
Did this fix your issue?

**Comment by tid-kijyun** [comment]
This problem is solved in the current version. If you still have problems please feel free to report.
