### ISSUE TITLE
CSS selector using wrong?

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [tid-kijyun/Kanna#175]
### Description:
I have the following HTML snippet which I need to parse and retrieve the string inside the `value` attribute.

```html
</div><input type="hidden" name="javax.faces.ViewState" id="javax.faces.ViewState" value="H4sIAAAAAAAAAFVRv08CMRSuB4c/YxB" autocomplete="off" />
```

The following returns `nil`.

```swift
if let doc = HTML(url: url, encoding: .utf8) {
    let s = doc.at_css("input#javax.faces.ViewState")
    print(s)
}
```

Am I using the css methods wrong?

### Installation method:
- [ ] Carthage
- [x] CocoaPods(1.1.0 or later)
- [ ] Swift Package Manager
- [ ] Manually
- [ ] other: ()

### Library version:
- [ ] v2.1.1
- [x] other: (2.2.1)

### Xcode version:
- [ ] 8.1 (Swift 3) 
- [ ] 8.1 (Swift 2.3)
- [ ] 7.3.1
- [x] other: (Xcode 9.1)

**Comment by tid-kijyun** [comment]
Currently, the CSS selector in this library can not access the id attribute including dot.  
In this case, please use Xpath.

```
if let doc = HTML(url: url, encoding: .utf8) {
    let s = doc.at_xpath(//input[@id = 'javax.faces.ViewState'])
    print(s)
}
```

FYI:
Dots in the CSS selector represent class attributes.
Your CSS selector points to `<input id ='javax' class='faces ViewState'>`.

**Comment by tid-kijyun** [comment]
Supports CSS escape in the next release. It is already supported on the master branch. 06b3a720fa7d6c08ebcb72c38842cc977e8a9447

```
if let doc = HTML(url: url, encoding: .utf8) {
    let s = doc.at_css("input#javax\\.faces\\.ViewState")
    print(s)
}
```

Thank you for reporting.
