### ISSUE TITLE
Compilation error on ubuntu with the latest master

### ISSUE THREAD

**Issue by crarau** [tid-kijyun/Kanna#184]
### Description:

The compilation error generated by: https://github.com/tid-kijyun/Kanna/commit/235d3347e89cbde75a52601871cf79b6bfd09f13#diff-9b73360ff3583f879d4e0c8da382b397R279

Here are the ubuntu logs:

/opt/api/.build/checkouts/Kanna.git-5145327835563053965/Sources/Kanna/libxmlHTMLNode.swift:279:29: error: missing argument for parameter 'capacity' in call
        content?.deallocate()
                            ^
                            capacity: <#Int#>
Swift.UnsafeMutablePointer:273:17: note: 'deallocate(capacity:)' declared here
    public func deallocate(capacity: Int)
                ^
/opt/api/.build/checkouts/Kanna.git-5145327835563053965/Sources/Kanna/libxmlHTMLNode.swift:282:25: error: missing argument for parameter 'capacity' in call
    content?.deallocate()
                        ^
                        capacity: <#Int#>
Swift.UnsafeMutablePointer:273:17: note: 'deallocate(capacity:)' declared here
    public func deallocate(capacity: Int)

### Installation method:
- [ ] Carthage
- [ ] CocoaPods(1.1.0 or later)
- [x] Swift Package Manager
- [ ] Manually
- [ ] other: ()

### Library version:
- [ ] v2.1.1
- [ ] other: ()

### Xcode version:
- [ ] 8.1 (Swift 3) 
- [ ] 8.1 (Swift 2.3)
- [ ] 7.3.1
- [ ] other: ()

**Comment by crarau** [comment]
It's using Swift 4.0.3 on Ubuntu:
To workaround I'm using:        
.package(url: "https://github.com/tid-kijyun/Kanna.git", from: "4.0.0"),
before I was pointing to the master.

**Comment by tid-kijyun** [comment]
Sorry for taking so long. This problem has been fixed in version 4.0.1.
