### ISSUE TITLE
Getting No such module SwiftClibxml2 on all the files in the project (css.swift, Kanna.swift , Libxmlhtmldocument.swift,libxmlhtmlnode.swift,libxmlparseroption.swift

### ISSUE THREAD

**Issue by sindhujagit** [tid-kijyun/Kanna#200]
### Description:

Unable to build kanna due to no such module error on css.swift .
### Installation method:
- [ ] Carthage
- [ ] CocoaPods
- [ ] Swift Package Manager
- [x ] Manually
- [ ] other: ()

### Xcode version (optional):9.4

I used manual installation method and added the files and modules.When I build in Xcode , am getting error as :No such module swiftclibxm2 all 4 files - (css.swift, Kanna.swift , Libxmlhtmldocument.swift,libxmlhtmlnode.swift,libxmlparseroption.swift)
I also made sure I removed import Kanna on the file.

**Comment by tid-kijyun** [comment]
Closed because it is a problem in the old version.
Feel free to repost if the issue is not resolved.
