### ISSUE TITLE
Xcode 10.2 Beta Ambiguous use of 'init(cString:)' error

### ISSUE THREAD

**Issue by CenoX** [tid-kijyun/Kanna#206]
### Description: When try to build on Xcode 10.2 Beta with Swift 5, it gets " Ambiguous use of 'init(cString:)' " error.

Error from:
_libxmlHTMLNode.swift:43, 51_
_libxmlHTMLDocument.swift:175, 307_

I tried [quick fix](https://github.com/CenoX/Kanna/tree/fix/cStringInit) of it.
Can I open PR of it?

### Installation method:
- [ ] Carthage
- [*] CocoaPods
- [ ] Swift Package Manager
- [ ] Manually
- [ ] other: ()

### Kanna version (or commit hash): 
CocoaPods version 4.0.3

### swift --version
$ swift --version
Apple Swift version 5.0 (swiftlang-1001.0.45.7 clang-1001.0.37.7)
Target: x86_64-apple-darwin18.2.0
ABI version: 0.6

### Xcode version (optional):
Xcode 10.2 Beta

**Comment by tid-kijyun** [comment]
Thank you for your report. Unfortunately, this problem has been fixed.
https://github.com/tid-kijyun/Kanna/tree/swift5

However, it seems to me that you added an encoding related test to your quick fix. Did you have a problem there?
If there is a problem, please send a new pull request that focused on that. That would be helpful, thank you.
