### ISSUE TITLE
How to get a pretty formatted string from html string

### ISSUE THREAD

**Issue by mumensh** [tid-kijyun/Kanna#208]
### Description:
I need to have my html string as a pretty formatted string, like this

`"<html><body></br><h1 style=\"font-size:54px; text-align: center\">This is my head text</h1></br></br></br><h2 style=\"font-size:44px; margin: 20px\">This is my body text</h2></body></html>"`

The result is:
This is my head textThis is my body text

Is it possible to have the result like this:
### This is my head text

This is my body text

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Swift Package Manager
- [ ] Manually
- [ ] other: ()

### Kanna version (or commit hash):
4.0.2
### swift --version
4.2
### Xcode version (optional):
10.1

**Comment by emreisik95** [comment]
Hi there,

You need to use UITextView, NSAttributedString and html2attributedstring. 

Add under your ViewController class to this code:

extension Data {
    var html2AttributedString: NSAttributedString? {
        do {
            return try NSAttributedString(data: self, options: [.documentType: NSAttributedString.DocumentType.html, .characterEncoding: String.Encoding.utf8.rawValue], documentAttributes: nil)
        } catch {
            print("error:", error)
            return  nil
        }
    }
    var html2String: String {
        return html2AttributedString?.string ?? ""
    }
}

extension String {
    var html2AttributedString: NSAttributedString? {
        return Data(utf8).html2AttributedString
    }
    var html2String: String {
        return html2AttributedString?.string ?? ""
    }
}

You can use this as variableName.html2AttributedString.

**Comment by Krish-sysadmin** [comment]
Maybe close this too so less clutter in "open issues"? @tid-kijyun

**Comment by tid-kijyun** [comment]
This is not the role of the parser.
