### ISSUE TITLE
Not an issue - Where can I donate towards this amazing library's author?

### ISSUE THREAD

**Issue by Pranoy1c** [tid-kijyun/Kanna#214]
I had been struggling with another library for days and thought my XPath had issues. Ultimately, I switched to this library and it solved 3 of my issues. They were all stemming from bugs in the other library. This library works wonderfully.

Is there a place I can donate a few bucks towards the author?

**Comment by tid-kijyun** [comment]
Thank you for using Kanna. I'm happy enough with just your feelings.

I can receive it in BTC: 3KW5YFxKujWkgGycf66Kh3jpZj14KGHggY
or I would be grateful if you would donate to [mozilla](https://donate.mozilla.org/en-US/?utm_source=foundation.mozilla.org&utm_medium=referral&utm_content=header&test=ost&test=htl) I support. 

I appreciate your support.
