### ISSUE TITLE
Undefined symbols

### ISSUE THREAD

**Issue by PeHk** [tid-kijyun/Kanna#221]
### Description:
Hi there, 

I'm newbie in Swift, I need to use packages for HTML parsing - in Simulator all works fine, but when I tried to have app on my iPhone Xs following errors appears. I think the problem is with libxml2 - I added it to user paths, to libraries, I changed everything what I found on StackOverflow, but nothing helps me out. Please can you give me advice? 

Thanks!

<img width="1103" alt="Snímka obrazovky 2019-12-21 o 9 36 25" src="https://user-images.githubusercontent.com/32091206/71305499-8aafba80-23d5-11ea-9701-2f1f94abd0da.png">

### Installation method:
- [ ] Carthage
- [ ] CocoaPods
- [x] Swift Package Manager
- [ ] Manually
- [ ] other: ()

**Comment by tid-kijyun** [comment]
When using on iOS, we recommend using Carthage or CocoaPods.
Please tell me if you have a reason to use Swift Package Manager(SwiftPM).

---
Currently, this library's SwiftPM is only available on macOS or Linux.  
I'm waiting for SwiftPM to provide multi-platform support for system libraries. 😓

**Comment by PeHk** [comment]
Hi,

Thank you for your answer! As I mentioned before, I am newbie in swift and package manager looks like simplest way to add other libraries. I will try it with cocoa pods or Carthage and I will inform you about progress! 

Thanks a lot for now!  🙂

**Comment by PeHk** [comment]
Solved! Thank you a lot!
