### ISSUE TITLE
Could not get some of amazon url preview

### ISSUE THREAD

**Issue by pmbct** [tid-kijyun/Kanna#224]
### Description:
https://www.amazon.com/dp/B07P3ZDGFH/ref=cm_sw_r_cp_api_i_QvcvEb6Q0P32N

### Installation method:
- CocoaPods
### Kanna version (or commit hash):
5.0.0
### swift --version
4.2

**Comment by Krish-sysadmin** [comment]
@pmbct Might want to describe this in more detail? Perhaps adding some code snippets?

**Comment by tid-kijyun** [comment]
If the website uses asynchronous loading, you need to devise a way to get the HTML. (For example: use WKWebView)
This is not the role of Kanna (HTML parser), so detailed explanation is omitted here.

If you have other issues please add more details and reopen.
