### ISSUE TITLE
Xpath not working Xcode 11.4 iOS 13.4

### ISSUE THREAD

**Issue by onurgenes** [tid-kijyun/Kanna#232]
### Description:
Xpath was working with Kanna 5.0.0 but it doesn't right now. You can check this issue on [eksi project](https://github.com/onurgenes/eskiclient).

If you go to this page https://eksisozluk.com/basliklar/bugun/1 and try select with `//*[@id='content-body']/ul/li/a` it returns 0 element. But in 5.0.0, it is returning  25 elements.

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Swift Package Manager
- [ ] Manually
- [ ] other: ()

### Kanna version (or commit hash):
5.2.0
### swift --version
5.2
### Xcode version (optional):
11.4

**Comment by tid-kijyun** [comment]
Thank you for your report.
I've just released v5.2.1 which fixes this issue.

**Comment by onurgenes** [comment]
Thank you for such a beautiful library!

Looking like it is resolved 👍🏻
