### ISSUE TITLE
 Is there a way to parse part of HTML instead of parsing full HTML?

### ISSUE THREAD

**Issue by alphonse1234** [tid-kijyun/Kanna#234]
### Description:

Currently I'm using XMLParser to get rss url from xml. Then parsing full html document from the url which got from xml. Lastly, search needed element and retrieve data.

But it takes too much time to parse full html and search element.

I'm extracting always same element

`<meta property="#element what I'm searching for#" content="#text I'm retrieving#">`
which is located in

`<head></head>`

So I don't want to wait for converting all html file.

Is there any way to do it?

or

Is there any way to do it faster?

This is my code parsing full html and getting element.

```
do {
      let doc = try HTML(url: url, encoding: .utf8)
      for string in doc.xpath("//meta[@property=\"og:title\"]") {
          if let result = string["content"]{
           completion(result)
          }
}
      } catch let error {
           print(error.localizedDescription)
         }

```

### Installation method:
- [ ] Carthage
- [ㅇ ] CocoaPods
- [ ] Swift Package Manager
- [ ] Manually
- [ ] other: ()

### Kanna version (or commit hash):
5.2.0
### swift --version
5.0
### Xcode version (optional): 11.2.1

**Comment by tid-kijyun** [comment]
Version 5.2.0 has a problem with HTML parsing.
Please use version **5.2.1**.

**Comment by jangchangsoon** [comment]
Ok, I’ll update. Do you have any idea with my question? Thanks.

**Comment by tid-kijyun** [comment]
I think it takes time to get the HTML from the server.
Separating the HTML get and parsing processes will reveal what's wrong.

```swift
do {
    // (1) Get HTML
    let data = try Data(contentsOf: url)

    // (2) Parse HTML
    let doc = try HTML(html: data, encoding: .utf8)
    for string in doc.xpath("//meta[@property=\"og:title\"]") {
        if let result = string["content"] {
           completion(result)
        }
    }
} catch let error {
    print(error.localizedDescription)
}
```

If the (1) part takes a lot of time:
There is nothing I can do because it has nothing to do with parsing.

If the (2) part takes a lot of time:
Please let us know the detailed situation.

Thanks.

**Comment by alphonse1234** [comment]
Oh, I see. Thank you
