### ISSUE TITLE
Speedup CSS.swift - CSS selector to XPath

### ISSUE THREAD

**Issue by nilsnilsnils** [tid-kijyun/Kanna#243]
### Description:
Hi. 

I use the _CSS.swift_ to convert CSS selectors to XPath to apply a list of CSS rules to my SVG Document.
That works perfectly :).

But I have some performance issues. Every conversion (CSS selector to XPath) takes around 5ms. When I have 100 CSS selectors it takes up to 500ms.

The question:
Is there a possibility to speed up the function ?
Do you have any tips for me how I can speed up the process (other than doing it parallel) ?

Thanks.
Thanks for your great work 👍  🥇 

### Kanna version (or commit hash):
master/Sources/Kanna/CSS.swift

**Comment by tid-kijyun** [comment]
@nilsnilsnils 
I have committed the latest code that has improved performance. Please try the latest master if you like.

**Comment by nilsnilsnils** [comment]
Thanks :)

Maybe you can answer me a question.

Short: 
I apply the css rules to my svg tree as described in my last comment.

I have my css file and my svg file.

Now have a loop over all css rules and find all elements for the css selector. To find the elements I use XPath on the svg document.

If I do that and I have many css rules the code to finde the elements via XPath go through the complete svg tree every time which is not very fast.

Is there a better way to apply all the css rules to my tree?

Thanks :)
