### ISSUE TITLE
Kanna/libxmlHTMLNode.swift:144: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value

### ISSUE THREAD

**Issue by qoli** [tid-kijyun/Kanna#247]
### Description:
Kanna/libxmlHTMLNode.swift:144: Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value

### Installation method:
- [ ] Carthage
- [x] CocoaPods
- [ ] Swift Package Manager
- [ ] Manually
- [ ] other: ()

### Kanna version (or commit hash):
5.2.4

### swift --version
swift 5

**Comment by Krish-sysadmin** [comment]
I can fix this. Can someone assign this to me? @qoli

**Comment by Krish-sysadmin** [comment]
@tid-kijyun Doesn't my commit you merged and modified already fix this issue too. The "line 144" thing. So maybe close this?

**Comment by tid-kijyun** [comment]
duplicate #242
