### ISSUE TITLE
File not found in Xcode 13.0 beta

### ISSUE THREAD

**Issue by tatsuz0u** [tid-kijyun/Kanna#248]
### Description:
```
Invalid Exclude '…/SourcePackages/checkouts/Kanna/Sources/Sources/Kanna.h': File not found.
Invalid Exclude ‘…/SourcePackages/checkouts/Kanna/Sources/Tests/KannaTests/Data': File not found.
Invalid Exclude '…/SourcePackages/checkouts/Kanna/Sources/Sources/Info.plist': File not found.
```

### Installation method:
- [ ] Carthage
- [ ] CocoaPods
- [x] Swift Package Manager
- [ ] Manually
- [ ] other: ()

### Kanna version (or commit hash):
5.2.4
### swift --version
5.5
### Xcode version (optional):
13.0 beta

**Comment by tid-kijyun** [comment]
Let's wait and see for the next beta.
note: Xcode 13.0 beta (13A5154h)

**Comment by tatsuz0u** [comment]
Reproduced in Xcode 13.0 beta 2 (13A5155e).

**Comment by scannillo** [comment]
👋 Hello - if you look at the[ XCode 13 release notes](https://developer.apple.com/documentation/xcode-release-notes/xcode-13-beta-release-notes) you will see this under "Resolved Issues"

> Improved the diagnostic information that Swift Package Manager returns when file paths in package manifests are invalid. Specifying a nonexistent or invalid path for a source file or resource now produces an error. (60708059, 60745311, 64176116)

So, I think this isn't a bug and means that one of the files listed under `exclude` in your Package.swift isn't at the correct filepath.
