### ISSUE TITLE
branch Swift 2 not available 

### ISSUE THREAD

**Issue by srGritsuk** [tid-kijyun/Kanna#25]
pod logs:

[!] Error installing Kanna
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

**Comment by tid-kijyun** [comment]
You can clone with https.
URL "git@github.com:tid-kijyun/Kanna.git" needs to be replaced with "https://github.com/tid-kijyun/Kanna.git".

```
use_frameworks!
pod 'Kanna', :git => "https://github.com/tid-kijyun/Kanna.git", :branch => "feat/Swift2"
```

Thanks.
