### ISSUE TITLE
Use in Projects

### ISSUE THREAD

**Issue by zzforapple** [tid-kijyun/Kanna#28]
hey , i know it's a framework , but i don't know how to use them in my project for ios.
i tried to build Kanna.xcodeproj , then in build folder -> Release-iphonesimulator a framework made ( Kanna.framework ) , i added it to my project , then >>  import Kanna and when i tried to run , i got a error , something was missed ... i just found this way of making frameworks from google , i don't know if i did it right .
 i need Kanna :)

**Comment by tid-kijyun** [comment]
Please use `Release-iphoneos/Kanna.framework`. (not Release-iphonesimulator/Kanna.framework)

You can build Kanna.xcodeproj for iOS Device.
![build_settings](https://cloud.githubusercontent.com/assets/1665104/9615346/77e771e2-5132-11e5-9b7b-89728cd6d5e9.png)
