### ISSUE TITLE
Edit node values

### ISSUE THREAD

**Issue by tid-kijyun** [tid-kijyun/Kanna#30]

**Comment by shahan312** [comment]
Hey @tid-kijyun, I would love to help build this feature out. Would you be able to point me in the right direction, and I can submit a PR.

**Comment by tid-kijyun** [comment]
Hi @shahan312 

Thanks, that would be great.
Would you follow this protocol?

```
// Kanna.swift
public protocol SearchableNode: Searchable {
    var text: String? { get }
    var toHTML:      String? { get }
    var innerHTML: String? { get }
    var className: String? { get }
    var tagName:   String? { get }
    var content: String { get set }     // New property
}
```

#### Usage:
```
if let doc = HTML(html: "<div>abc</div>", encoding: NSUTF8StringEncoding),
        var node = doc.css("div").first {
    print(node.text)       // => Optional("abc")
    print(node.content) // => abc

    node.content = "Awesome"

    print(node.text)       // => Optional("Awesome")
    print(node.content) // => Awesome
}
```

**Comment by shahan312** [comment]
Yep! Should the type of the `content` property be `String?`, since the other properties in the protocol are also optional?

**Comment by tid-kijyun** [comment]
> Should the type of the `content` property be `String?`

That’s more like it. :+1:

Thanks

**Comment by tid-kijyun** [comment]
Hi @shahan312 

I've implemented this feature.
Thank you for the kind proposal.
