### ISSUE TITLE
NSISOLatin2StringEncoding 

### ISSUE THREAD

**Issue by fortmarek** [tid-kijyun/Kanna#34]
I'm trying to parse this site: http://old.gjk.cz/suplovani.php 
The problem is it's in Czech which in Swift encoding means NSISOLatin2StringEncoding but for whatever  reason with this code it doesn't work:        
 let url = NSURL(string: "http://old.gjk.cz/suplovani.php")
        let task = NSURLSession.sharedSession().dataTaskWithURL(url!) {
            data, response, error in
            if let table = Kanna.HTML(html: data!, encoding: NSISOLatin2StringEncoding) {
                print(table.title!)
            }
The output is table = nil
If I use NSISOLatin1StringEncoding though, table != nil, but the output is Bakaláøi - Suplování because of the wrong encoding. Any ideas why NSISOLatin2StringEncoding doesn't work? It works when I don't use Kanna framework with print(NSString(data: data!, encoding: NSISOLatin2StringEncoding))
I am using XCode beta 7.1.

**Comment by tid-kijyun** [comment]
Please use `NSWindowsCP1250StringEncoding`.

**Comment by fortmarek** [comment]
That works like magic! Thanks a lot for this and for your repository, I'm new to coding so I'm missing a lot of basic stuff and this is super helpful.
