### ISSUE TITLE
tvOS support

### ISSUE THREAD

**Issue by larsschwegmann** [tid-kijyun/Kanna#36]
It would be nice to support tvOS. I tried to add a tvOS target on my own, but I have no idea how to properly link libxml. It would be really nice if i could get it working on the apple tv.

**Comment by cezheng** [comment]
@larsschwegmann I just happened to walked into this issue and I happened to have a similar repo like this one that uses libxml2. For your reference on how to link libxml2 to a tvOS target
https://github.com/cezheng/Fuzi

**Comment by tid-kijyun** [comment]
Hi @larsschwegmann 

Added support for tvOS and watchOS.

**Comment by larsschwegmann** [comment]
Awesome! Thanks @cezheng & @tid-kijyun 👍🏻
