### ISSUE TITLE
Non-modular header inside framework module compile error using Xcode 7.1  

### ISSUE THREAD

**Issue by salabaha** [tid-kijyun/Kanna#37]
Unable to build Kanna using cocopods and Xcode 7.1. 

The following error occurred. 

![screen shot 2015-10-22 at 1 59 11 pm](https://cloud.githubusercontent.com/assets/1324248/10663639/96f61394-78c5-11e5-8745-faa4384375e3.png)

.

**Comment by tid-kijyun** [comment]
Fixed it.
Thank you.

**Comment by salabaha** [comment]
Wow, It was fast. Thanks.

**Comment by fortmarek** [comment]
I am having the very same error with XCode 7.2, any idea how to fix it? (people often suggest to set "Allow non-modular modules" to YES, but that didn't work for me)
