### ISSUE TITLE
Different results

### ISSUE THREAD

**Issue by Arti3DPlayer** [tid-kijyun/Kanna#39]
for this xpath:
```(//a[contains(@href, 'product')])[1]/@href```

at browser it return:
```
product/7721628;jsessionid=W0eC3Cam8rXg5hLeBODUFQ__.node2?site=sr:SEARCH:MAIN_RSLT_PG
```

with your library:
```
href="product/7721628;jsessionid=e8za0YLN1vFhtqK7t6up2A__.node4?site=sr:SEARCH:MAIN_RSLT_PG"
```

**Comment by tid-kijyun** [comment]
Hi @Arti3DPlayer 

Do you use `innerHTML` propety by any chance?
If that's the case, please use `text` property.

Example for:
```
if let doc = HTML(html: html, encoding: NSUTF8Encoding) {
    for node in doc.xpath("(//a[contains(@href, 'product')])[1]/@href") {
        print(node.text)
    }
}
```

**Comment by Arti3DPlayer** [comment]
thanks, i used ```node.toHTML```. But can you explain what different between ```toHTML``` and ```text```

**Comment by tid-kijyun** [comment]
`toHTML`:
It will return the whole of node.

`text`:
It will return the text part of node.
