### ISSUE TITLE
Does library support concat and another logical operations?

### ISSUE THREAD

**Issue by Arti3DPlayer** [tid-kijyun/Kanna#40]
Have troubles with queries that contains logical operations. They always return empty results. I saw sources you use concat and other logical operations here: https://github.com/tid-kijyun/Kanna/blob/master/Source/CSS.swift#L189 . Why my is not work?
```
for node in doc.xpath("concat((//a/@href)[1], (//a/@href)[2])") {
            output += node.toHTML!`
            output += node.text!
        }
```

**Comment by Arti3DPlayer** [comment]
i found the solution i guess. This is because i return string, not dom element :( Is there a solution, how to make it works ?

**Comment by tid-kijyun** [comment]
There are no way at the moment.
This method can only use to get node.

The following will be the same result:
```
for node in doc.xpath("(//a/@href)[1]|(//a/@href)[2]") {
    output += node.text!
}
```

**Comment by tid-kijyun** [comment]
Added supported in the next major version. (branch [2.0.0](https://github.com/tid-kijyun/Kanna/tree/2.0.0))

```
output += doc.xpath("concat((//a/@href)[1], (//a/@href)[2])").stringValue
```

Thanks.
