### ISSUE TITLE
How do i get the childs of a tag?

### ISSUE THREAD

**Issue by ankit1ank** [tid-kijyun/Kanna#42]
I have been able to extract data from the outer most XML tag. However, I have not been able to figure out how to extract data from sub tags. For eg.

<Person>
<Name>Bob</Name>
<Age>21</Age>
</Person>
<Person>
<Name>Alice</Name>
<Age>20</Age>
</Person>

How do i get the name and age in the example XML shown above?

**Comment by tid-kijyun** [comment]
Hi @ankit1ank 

For example:
```
if let doc = XML(xml: xml, encoding: NSUTF8StringEncoding) {
    for person in doc.css("Person") {
        print(person.at_css("Name")?.text)
        print(person.at_css("Age")?.text)
    }
}
```

FYI: The XML document is required root node.

```
<RootNode>
<Person>
<Name>Bob</Name>
<Age>21</Age>
</Person>
<Person>
<Name>Alice</Name>
<Age>20</Age>
</Person>
</RootNode>
```

**Comment by Francescu** [comment]
@tid-kijyun your example may extract `Person` at any sublevels, not only `Person` children of the tag, right?

```
<RootNode>
  <Person>
    <Name>Bob</Name>
    <Age>21</Age>
  </Person>
  <Person>
    <Name>Alice</Name>
    <Age>20</Age>
    <Father>
       <Person>
         <Name>Bob</Name>
      </Person>
    </Father>
  </Person>
</RootNode>
```

You'd get 2 Bob?

**Comment by tid-kijyun** [comment]
Exactly.

If you want to search "Person" immediately below the RootNode, please write as follows:
```
if let doc = XML(xml: xml, encoding: NSUTF8StringEncoding) {
    for person in doc.css("RootNode>Person") {
        print(person.at_css("Name")?.text)
        print(person.at_css("Age")?.text)
    }
}
```

Please refer to the link for more information on the CSS selector .
http://www.w3.org/TR/css3-selectors/
