### ISSUE TITLE
Can you give more details in how to import the library manually?

### ISSUE THREAD

**Issue by maghrab** [tid-kijyun/Kanna#43]
I followed your instructions, but still 

import Kanna gives an error ( No such module 'Kanna' )

**Comment by tid-kijyun** [comment]
Hi @maghrab 

For manually, this library don't need import and namespace in your code.

example code:
```
//import Kanna  //<--- Don't need this line

let html = "<html>...</html>"

if let doc = HTML(html: html, encoding: NSUTF8StringEncoding) {  // Don't need 'Kanna.' namespace.
    println(doc.title)

    // Search for nodes by CSS
    for link in doc.css("a, link") {
        println(link.text)
        println(link["href"])
    }

    // Search for nodes by XPath
    for link in doc.xpath("//a | //link") {
        println(link.text)
        println(link["href"])
    }
}
```

**Comment by maghrab** [comment]
That also mean, I have to remove import libxml2 from the swift files?

**Comment by tid-kijyun** [comment]
No.
Please delete "import Kanna" in your code.

**Comment by maghrab** [comment]
Thanks

**Comment by maghrab** [comment]
I am still unable to compile, import libxml2 gives an error now same as import Kanna previously. 

I am using Xcode 7 and for some reason I cannot find libxml2.dylib

**Comment by tid-kijyun** [comment]
Oops, the latest version has changed the manually installation method.
Sorry, I've updated the document.

Thanks

**Comment by maghrab** [comment]
It works but only when I remove import libxml2 from the 2 libxml swift files. Can you confirm if that's needed?

**Comment by maghrab** [comment]
It's working without import libxml2

**Comment by tid-kijyun** [comment]
You should not need remove it.
But it's ok if it's working.

**Comment by maghrab** [comment]
Thanks
