### ISSUE TITLE
CSS3 Selector does not seem to be working

### ISSUE THREAD

**Issue by jbehrens94** [tid-kijyun/Kanna#45]
Hi guys!

I currently run into trouble with this selector `#content > p:not(.article-meta)`.
When I run this selector into [JSFiddle](http://jsfiddle.net/v123geea/), the right parts are coloured red. But Kanna returns also the p.article-meta with the same selector.

Is this expected behaviour, or am I using the libs wrong?

**Comment by tid-kijyun** [comment]
Fixed it.

Thanks.
