### ISSUE TITLE
Why not support Objective-C?

### ISSUE THREAD

**Issue by zcill** [tid-kijyun/Kanna#48]

**Comment by tid-kijyun** [comment]
Because I don't need it.
I might do support objective-c if someone wants it.

**Comment by zcill** [comment]
Thanks for your reply. I'm preparing to learn Swift, could you give me some suggestions?

**Comment by tid-kijyun** [comment]
What’s it about?
I can answer only related matters to this library.

**Comment by zcill** [comment]
haha, ok, thank you all the same.

**Comment by HePingLaoSan** [comment]
looking forward to supporting objective-c!!!
