### ISSUE TITLE
No such module 'libxm12'

### ISSUE THREAD

**Issue by juniorProgrammer** [tid-kijyun/Kanna#51]
I install this to my project via pods but can't seem to get it to work

**Comment by tid-kijyun** [comment]
Hi @juniorProgrammer 

Are you using the latest version of the pods?
Could you please use version 0.39.0 or later.

Please check the version:
```
$ pod --version
```

Thanks

**Comment by tid-kijyun** [comment]
If your problem is not solved, please reopen this issue.

Thanks
