### ISSUE TITLE
Kanna was compiled with optimization - stepping may behave oddly; variables may not be available.

### ISSUE THREAD

**Issue by nunogoncalves** [tid-kijyun/Kanna#52]
So I was using Kanna to parse some HTML on my iOS app. 

Everything works well on Debug mode no problem.

When I tested the app on TestFlight it just crashed. Took me a while to figure out the problem.
It happens only in Release mode so I went ahead and changed the scheme to Release mode.

Firing up the app it crashes as the TestFlight version, as "expected".

The problem resides in the class `libxmlHTMLNode` in the following method: 

```swift
private func libxmlGetNodeContent(nodePtr: xmlNodePtr) -> String? {
    let content = xmlNodeGetContent(nodePtr)
    if let result  = String.fromCString(UnsafePointer(content)) {
        content.dealloc(1)
        return result
    }
    content.dealloc(1)
    return nil
}
```
The line `let content = xmlNodeGetContent(nodePtr)` has a EXC_BAD_ACCESS and when I try to print out the nodePtr I get the following message:

>Kanna was compiled with optimization - stepping may behave oddly; variables may not be available.

So I went ahead and turned `Swift Compiler Optimization Level to None[-Onone] and the app runs propperly. 

My app is a Swift app using Kanna installed via CocoaPods. 

Not sure what I can do. 
Anybody had this problem before?

**Comment by tid-kijyun** [comment]
Hi @nunogoncalves 

Does it occur only in TestFlight?

**Comment by nunogoncalves** [comment]
No no. Changing my scheme and running in locally it also happens.

**Comment by tid-kijyun** [comment]
I tried the same option you used, but couldn't reproduce it.
Could you please tell me part of the parse code and HTML that has crashed?

**Comment by nunogoncalves** [comment]
Sorry for the delay. You are right. The message has nothing to do with the crash. 

I tried debugging it a bit more and it's even weirder. I have a loop and for each iteration I'm trying to get a value. The weird thing is that it doesn't happen always on the same iteration...

The whole project is available here (branch Trending-Repos):
https://github.com/nunogoncalves/iOS-OctoPodium/tree/Trending-Repos

This is my code that starts the problem:
https://github.com/nunogoncalves/iOS-OctoPodium/blob/Trending-Repos/OctoPodium/Use%20Cases/Repositories/CreateListFromHTML.swift#L46

Sometimes it happens on the first iteration, others second, or even third... 

I'm starting to think this might have something to do with threading...

The html is the one in this page: 
https://github.com/trending?since=today

**Comment by tid-kijyun** [comment]
I've sent pull-request to your repository.
Please check it.

**Comment by nunogoncalves** [comment]
That works... Thanks... Very sorry for the trouble.

**Comment by beforeold** [comment]
so how is the problem resolved, i ran into some similar one?

**Comment by tid-kijyun** [comment]
@beforeold 

https://github.com/nunogoncalves/iOS-OctoPodium/commit/c49f9755dee859c0e62bdb39d39abbfd87e2b11d

**Comment by beforeold** [comment]
@tid-kijyun Thanks for you rely. I am struggling with a similar issue right now. Yes, I have already read the code you committed, unfortunately I still don't know why the compiler complains about optimazation.
