### ISSUE TITLE
extension XMLNodeSet / Argument passed to call that takes no arguments

### ISSUE THREAD

**Issue by ixeau** [tid-kijyun/Kanna#60]
I just manually implemented Kanna and got the following parser error in Kanna.swift:
Edit: The error occurs even when it's installed via CocoaPods.

<img width="571" alt="bildschirmfoto 2016-03-09 um 17 21 11" src="https://cloud.githubusercontent.com/assets/5813406/13642075/5c51afaa-e61b-11e5-89d6-25e4fb8350c5.png">

Tested with OS X El Capitan 10.11.3, Xcode 7.2.1, Swift-Project

**Comment by tid-kijyun** [comment]
Hi @martinlexow 

Current master repository supports Xcode7.3 beta, Swift 2.2 or later.
Could you please use the latest release version?
https://github.com/tid-kijyun/Kanna/releases/tag/1.0.5

Thanks

**Comment by martinlexow** [comment]
Hi @tid-kijyun 

I already tried using it with your 1.0.5 release yesterday and got the error I described above. Do I have to upgrade to Xcode7.3/Swift 2.2 or is there any way to get it running with Xcode 7.2.1?

**Comment by robinraintama** [comment]
Hi @tid-kijyun 

Do you have other option than upgrade to xcode 7.3 beta? I think 1.0.5 is still support swift 2.2 or later only

**Comment by tid-kijyun** [comment]
I suppose you download souce code from master repository, don't you?
Please download code from this URL. https://github.com/tid-kijyun/Kanna/archive/1.0.5.zip

If this does not solve the problem, please try the previous version(1.0.4).

Thanks

**Comment by DaveKlassen4** [comment]
Thanks v1.0.5 worked for me!

**Comment by robinraintama** [comment]
Ah it works. Sorry i think copy the wrong files. But now i got this

> Use of unresolved identifier 'Kanna'


For manual installation i dont need to do
`import Kanna` right?

**Comment by DaveKlassen4** [comment]
Thats what I did too, and the import does not seem to work as per the readme, however I am not exactly an XCode genius

**Comment by robinraintama** [comment]
Hi @DaveKlassen4 
So we have the same problem right? Have you try the 1.0.4?

**Comment by DaveKlassen4** [comment]
Yes, however I have never imported a module before, so it might take me longer than necessary to discover everything involved. Maybe I will try this again at a later time, when I understand the swift and  iOS IDEs/APIs a bit better.

**Comment by tid-kijyun** [comment]
> For manual installation i dont need to do `import Kanna` right?
That's right.

**Comment by robinraintama** [comment]
Do i miss something? It means xcode dont recognize Kanna.swift right?

**Comment by tid-kijyun** [comment]
@robinraintama 

No, It's ok just like that.
In the case of manual installation, Swift compiler does not create the ​`Kanna` ​namespace.

**Comment by robinraintama** [comment]
@tid-kijyun But why i got?

> Use of unresolved identifier 'Kanna'

**Comment by tid-kijyun** [comment]
@robinraintama 

> Use of unresolved identifier 'Kanna'

Because swift compiler does not create the ​Kanna ​namespace.
In the case of manual installation, It's normal, It's no problem.

Sample code for manual installation:
```
let html = "<html><body><a href='http://google.com'>link</a></body></html>"

if let doc = HTML(html: html, encoding: NSUTF8StringEncoding) {
    print(doc.title)

    // Search for nodes by CSS
    for link in doc.css("a, link") {
        print(link.text)
        print(link["href"])
    }

    // Search for nodes by XPath
    for link in doc.xpath("//a | //link") {
        print(link.text)
        print(link["href"])
    }
}
```

**Comment by tid-kijyun** [comment]
Please remove `Kanna.` prefix.

**Comment by DaveKlassen4** [comment]
doh! Doumo arigatou gozaimashita!

**Comment by robinraintama** [comment]
Ah it works!
I thought Kanna.swift is a class but it's not.
Thank you

**Comment by martinlexow** [comment]
I tried it again with your linked 1.0.5 version, installed it manually, and got a new error: '**No such module 'libxml2''**. It's an iOS project - but that's not the problem here, right? I appreciate any help!

**Comment by tid-kijyun** [comment]
@martinlexow 

Please refer to it. https://github.com/tid-kijyun/SampleKanna

**Comment by jacquelyn-tandang** [comment]
Hi @tid-kijyun 

I tried manual installation, removed import Kana and the Kana. name space but I am getting the following error:
Use of unresolved identifier HTML

**Comment by tid-kijyun** [comment]
> Use of unresolved identifier HTML

Please discuss here: #76.
