### ISSUE TITLE
Module Needs to be Recompiled with Latest Version of Xcode

### ISSUE THREAD

**Issue by nsalerni** [tid-kijyun/Kanna#61]
After updating Xcode to the latest version, I get the following error:

"/Users/nsalerni/Documents/GitHub/GODelays-iOS/GODelays/GODelays/FeedViewController.swift:11:8: Module file was created by an older version of the compiler; rebuild 'Kanna' and try again: /Users/nsalerni/Library/Developer/Xcode/DerivedData/GODelays-fzmhfgqmmokmdbfhgeigokyaqqar/Build/Products/Debug-iphonesimulator/Kanna.framework/Modules/Kanna.swiftmodule/x86_64.swiftmodule"

**Comment by tid-kijyun** [comment]
Hi @nsalerni 

How did you install the library? Pods, Carthage or Manually?

**Comment by nsalerni** [comment]
Pods

**Comment by tid-kijyun** [comment]
Kanna 1.0.6 is now available.
Please try `pod update`.

Thanks

**Comment by nsalerni** [comment]
It still fails with the same error

**Comment by nsalerni** [comment]
I even tried completely regenerating the POD files and then reinstalling

**Comment by tid-kijyun** [comment]
Xcode menu: `Window` > `Projects` > `Your Project`

Please delete the `Derived Data`:

![screen shot 2016-03-31 at 12 43 52 am](https://cloud.githubusercontent.com/assets/1665104/14148279/cdb9f37c-f6d9-11e5-91b5-a74b33c62332.png)

and rebuild your project.
