### ISSUE TITLE
Kanna.swift build failed

### ISSUE THREAD

**Issue by socialvanana** [tid-kijyun/Kanna#64]
extension XMLNodeSet: SequenceType {
    public typealias Generator = AnyGenerator<XMLElement>
    public func generate() -> Generator {
        var index = 0
        return AnyGenerator {  //  Argument passed to call that takes no arguments
            if index < self.nodes.count {
                let n = self.nodes[index]
                index += 1
                return n
            }
            return nil   //Type of expression is ambiguous without more context
        }
    }
}

**Comment by socialvanana** [comment]
Oh, I missed this issue already published

**Comment by Mystina** [comment]
Hi, how did you solve the problem? I have the same problem. Please let me know how you solved it?  Thanks very much!

**Comment by kundanjadhav** [comment]
How did you solved this issue?
