### ISSUE TITLE
Carthage doesn't work

### ISSUE THREAD

**Issue by cocoBavan** [tid-kijyun/Kanna#67]
`*** Building scheme "Kanna_tvOS" in Kanna.xcworkspace
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal arm64 /workspace/Carthage/Checkouts/Kanna/Sources/Kanna.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
/workspace/Carthage/Checkouts/Kanna/Sources/Kanna.swift:253:20: error: type of expression is ambiguous without more context
/workspace/Carthage/Checkouts/Kanna/Sources/Kanna.swift:247:29: error: argument passed to call that takes no arguments
A shell task (/usr/bin/xcrun xcodebuild -workspace /workspace/Carthage/Checkouts/Kanna/Kanna.xcworkspace -scheme Kanna_tvOS -configuration Release -sdk appletvos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal arm64 /workspace/Carthage/Checkouts/Kanna/Sources/Kanna.swift
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)`

**Comment by tid-kijyun** [comment]
Hi @cocoBavan 

What is the Xcode version that you are using? Kanna v1.0.6 required Xcode7.3.
Please use v1.0.5 if you use Xcode 7.2.

`github "tid-kijyun/Kanna" "1.0.5"`

Thanks

**Comment by cocoBavan** [comment]
Oh ok.. Thanks for letting me know.
