### ISSUE TITLE
use or abuse of css `::after` function causes hang

### ISSUE THREAD

**Issue by chrisco314** [tid-kijyun/Kanna#68]
I may well have been in error, but calling XMLElement.css with just the function "::after" appears to cause a loop / hang.  I am pretty new to CSS and Kanna, but was trying to find key value pairs in the following manner

	let label = detail.css("strong").first!
	let value = label.css("::after")

My program / script then hung, with a stack like this:

    #0	0x00007fff8c6f40a3 in malloc ()
    #1	0x00007fff913a8f34 in icu::RegexCompile::compile(UText*, UParseError&, UErrorCode&) ()
    #2	0x00007fff913a30db in icu::RegexPattern::compile(UText*, unsigned int, UParseError&, UErrorCode&) ()
    #3	0x00007fff913a2cdf in uregex_open ()
    #4	0x00007fff8e73db70 in -[NSRegularExpression initWithPattern:options:error:] ()
    #5	0x00000001000f25a3 in @nonobjc NSRegularExpression.init(pattern : String, options : NSRegularExpressionOptions) throws -> NSRegularExpression ()
    #6	0x00000001000f2440 in NSRegularExpression.__allocating_init(pattern : String, options : NSRegularExpressionOptions) throws -> NSRegularExpression ()
    #7	0x00000001000eff5e in (firstMatch in _CA6A004099612D342CE85B6160D34CF2)(String) -> (str : String) -> NSTextCheckingResult? at /path/Pods/Kanna/Source/CSS.swift:83
    #8	0x00000001000ecc55 in (getAttribute in _CA6A004099612D342CE85B6160D34CF2)(inout String, skip : Bool) -> String? at /path/Pods/Kanna/Source/CSS.swift:216
    #9	0x00000001000e908e in static CSS.toXPath(String) -> String? at /path/Pods/Kanna/Source/CSS.swift:59
    #10	0x00000001001046dd in libxmlHTMLNode.css(String, namespaces : [String : String]?) -> XMLNodeSet at /path/Pods/Kanna/Source/libxml/libxmlHTMLNode.swift:144
    #11	0x0000000100104a6c in libxmlHTMLNode.css(String) -> XMLNodeSet at /path/Pods/Kanna/Source/libxml/libxmlHTMLNode.swift:155

I have other means of getting the element I want, but wasn't expecting a hang.  It is likely that you need to pass a path to after, I was just hoping that I could get the next sibling for a given element.

Otherwise, I'm really enjoying the library - Thanks!

**Comment by tid-kijyun** [comment]
I've just fixed this issue.

⚠️*Note: These CSS selector is not supported.*
* `:after`
* `:before`
