### ISSUE TITLE
Does not parse latin characters and cedilla

### ISSUE THREAD

**Issue by vihanggodbole** [tid-kijyun/Kanna#69]
Whenever I parse content that contains Spanish letters like ç, ó etc it fails to do so. Instead, i get outputs like -
Ã³ for ó
Ã± for ñ
Ã§ for ç 
Help would be much appreciated!

**Comment by tid-kijyun** [comment]
Hi @vihanggodbole 

Do you specify a character code encoding that matches the HTML text?

```
// There is a need to specify the character code encoding that matches the HTML text to the second argument.
if let doc = HTML(html: "...", encoding: MATCH_ENCODING) {
}
```

Thanks

**Comment by vihanggodbole** [comment]
Yes I did. I'm using NSUTF8StringEncoding and the website is also using utf-8.

**Comment by tid-kijyun** [comment]
Please tell me the website that you want to parse, if possible.

**Comment by vihanggodbole** [comment]
Here - [www.grup14.com](url)

**Comment by tid-kijyun** [comment]
I have tried the code below.
```
if let doc = HTML(url: NSURL(string: "https://grup14.com")!, encoding: NSUTF8StringEncoding) {
    for node in doc.css("div.gcard-title>h1") {
        print(node.innerHTML)
    }
}
```

output:
```
Barcelona agrees €5.5m settlement for two tax offences
Iniesta: 'What we’ve done over the last 10-12 years is unthinkable'
Prosecutor asks that Neymar be trialed for corruption in the DIS case
Mascherano: 'I don't want to leave Barça with a bad taste in my mouth"
Why Barcelona continues to sign players from Traffic?
Marc Bartra joins Borussia Dortmund
...
```

It appears to be no problem. (Please look at the fourth line.)

Do you use the Alamofire?

**Comment by vihanggodbole** [comment]
Wow. My output is - 

> Barcelona agrees â¬5.5m settlement for two tax offences
> Iniesta: 'What weâve done over the last 10-12 years is unthinkable'
> Prosecutor asks that Neymar be trialed for corruption in the DIS case
> Mascherano: 'I don't want to leave BarÃ§a with a bad taste in my mouth"
> Why Barcelona continues to sign players from Traffic?
> Marc Bartra joins Borussia Dortmund
> Robert FernÃ¡ndez: "Dani Alves has decided to leave, it's a personal decision and we accept that."
> Barcelonaâs academy continues to be the best in Europe
> The Pep Episodes (XL)
> Rating the players in the Spanish Cup final win vs Sevilla
> Tiki Taka - Barcelona 2:0 Sevilla
> Rating the Barcelona players in the win vs Granada
> 

Yes, I use Alamofire. Is that causing the issue?

**Comment by tid-kijyun** [comment]
Please specify the encoding to Alamofire.

e.g.
```
Alamofire.request(.GET, NSURL(string: "https://grup14.com")!)
    .responseString(encoding: NSUTF8StringEncoding) { (request, response, string, error) in
        if let doc = HTML(html: string!, encoding: NSUTF8StringEncoding) {
             for node in doc.css("div.gcard-title>h1") {
                print(node.innerHTML!)
            }
        }
    }
```

**Comment by vihanggodbole** [comment]
Ooh. It worked perfectly! Thanks a lot :D Both for the help and this awesome library :)

**Comment by tid-kijyun** [comment]
🎉
