### ISSUE TITLE
Fatal crash with HTML parsing

### ISSUE THREAD

**Issue by GZaccaroni** [tid-kijyun/Kanna#72]
When i try to parse that HTML, Kanna Crashes with error: 

> XMLNodeSet.subscript.getter fatal error: Index out of range

HTML: 
`<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.9.3</center>\r\n</body>\r\n</html>\r\n`

**Comment by tid-kijyun** [comment]
Hi @GZaccaroni 

Please tell me your crashed code.

Thanks

**Comment by GZaccaroni** [comment]
`                if let doc = Kanna.HTML(html: response.data!, encoding: NSUTF8StringEncoding) {
                    if let csrftoken = doc.css("input[name=\"csrfmiddlewaretoken\"]")[0]["value"]{

                    }
                }else{
                    NSNotificationCenter.defaultCenter().postNotificationName("erroreCaricamento", object: nil)
                    NSNotificationCenter.defaultCenter().postNotificationName("login", object:nil, userInfo: ["messaggio": "nonDisponibile"])
                }`

It crashes in the first line, response.data! contains the html provided above.

**Comment by tid-kijyun** [comment]
It seems there is a problem in the second line.

```
if let doc = Kanna.HTML(html: response.data!, encoding: NSUTF8StringEncoding) {
    if let csrftoken = doc.css("input[name=\"csrfmiddlewaretoken\"]").first?["value"] {
    }
} else {
    NSNotificationCenter.defaultCenter().postNotificationName("erroreCaricamento", object: nil)
    NSNotificationCenter.defaultCenter().postNotificationName("login", object:nil, userInfo: ["messaggio": "nonDisponibile"])
}
```

**Comment by GZaccaroni** [comment]
@tid-kijyun thanks for the reply... you're right... i'm sorry.
