### ISSUE TITLE
error: could not build Objective-C module 'libxml2' when use pod Kanna 1.0.6 with CocoaPods 1.0.0

### ISSUE THREAD

**Issue by nixzhu** [tid-kijyun/Kanna#75]
It works when use use pod Kanna 1.0.2 with CocoaPods 1.0.0.

```
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "libxml2-kanna.h"
        ^
/Users/nix/dev/github/clones/Yep/Pods/Kanna/Modules/libxml2-kanna.h:1:9: note: in file included from /Users/nix/dev/github/clones/Yep/Pods/Kanna/Modules/libxml2-kanna.h:1:
#import <libxml2/libxml/HTMLtree.h>
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator9.3.sdk/usr/include/libxml2/libxml/HTMLtree.h:15:10: error: 'libxml/xmlversion.h' file not found
#include <libxml/xmlversion.h>
         ^
<unknown>:0: error: could not build Objective-C module 'libxml2'
```

**Comment by kiliankoe** [comment]
Having the same issue. Downgrading to 1.0.2 solved it for now although I'd really like to stay on the most current version.

**Comment by tid-kijyun** [comment]
Hi @nixzhu, @kiliankoe 

I can't reproduce this error.
Please tell me the following information:

1. Your Xcode version
1. Your Podfile

Thanks

**Comment by kiliankoe** [comment]
I'm on Xcode 7.3.1 (7D1014) with the following as my Podfile:

```ruby
use_frameworks!

target 'RSS_Example' do
  pod 'RSS', :path => '../'
  pod 'Kanna', '1.0.2' # now set to explicitly require 1.0.2

  target 'RSS_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
    pod 'Nimble', '~> 3.0'
  end
end
```

**Comment by nixzhu** [comment]
@tid-kijyun Now I working on an open source project, there is the Podfile: https://github.com/CatchChat/Yep/blob/develop/Podfile . You can build it for test (in develop branch) if need.

**Comment by tid-kijyun** [comment]
Thanks for your reply.
I'll investigate this issue.

**Comment by tid-kijyun** [comment]
Hi @nixzhu 

You need to add "$(SDKROOT)/usr/include/libxml2" to the Search Paths > Header Search Paths field.

![yep](https://cloud.githubusercontent.com/assets/1665104/15710141/9c0bf352-2843-11e6-8573-348c46536ae0.png)

Thanks

**Comment by tid-kijyun** [comment]
Hi @kiliankoe 

You need to add `s.xcconfig      = { 'HEADER_SEARCH_PATHS' => '$(SDKROOT)/usr/include/libxml2' }` to your [RSS.podspec](https://github.com/kiliankoe/RSS/blob/master/RSS.podspec) file.

Thanks

**Comment by kiliankoe** [comment]
Unfortunately that doesn't seem to be working 😕 Still receiving the mentioned errors with v1.0.6.

If I'm not mistaken `$(SDKROOT)/usr/include/libxml2` was already included in the header search paths of my pod before explicitly specifying this.

**Comment by nixzhu** [comment]
@tid-kijyun Thanks! But unfortunately it's not working that add "$(SDKROOT)/usr/include/libxml2" to YepShare Search Paths > Header Search Paths. I also try add `pod Kanna` in target YepShare in Podfile, after pod install, it will add this search path automatically. But when I build, failed with same error.

**Comment by tid-kijyun** [comment]
@nixzhu @kiliankoe 

Umm...Please try delete `Derived Data`.
`Xcode's menu > Window > Projects > [Your Project] > Delete`

**Comment by nixzhu** [comment]
@tid-kijyun Already try it, not work. Have you built Yep successful with pod Kanna 1.0.6?

**Comment by kiliankoe** [comment]
Same here, unfortunately 😕

**Comment by tid-kijyun** [comment]
@nixzhu 

Yes, I have. I'll look into it in more detail.

**Comment by kiliankoe** [comment]
Btw, not sure if it makes a difference: I had previously installed libxml2 via Homebrew, don't recall for what reason, but it seemed not to a dependency of anything, so I uninstalled it. Same problem though as before.

**Comment by Arclite** [comment]
FWIW, something that just worked for me (using Carthage, not CocoaPods), was deleting my `Carthage/Checkouts` directory and starting from just the Cartfile. I think the CocoaPods equivalent would be deleting `Pods` and re-running `pod install`.

Not sure if it's just voodoo, but there were definitely files removed from Kanna between 1.0.2 and 1.0.6 that Git noticed were missing after I did that—perhaps Xcode was still trying to reference them in a way that caused the `libxml2` error?

**Comment by tid-kijyun** [comment]
@nixzhu @kiliankoe @Arclite 

I've just released a new version of Kanna.
Please try the version [1.1.0](https://github.com/tid-kijyun/Kanna/releases/tag/1.1.0).

Thanks

**Comment by kiliankoe** [comment]
Seems to be working! Awesome, thank you so much! 😊

**Comment by iwheelbuy** [comment]
"$(SDKROOT)/usr/include/libxml2" solved the issue!

```
target 'Transport' do
   
   use_frameworks!
   
   pod 'RxCocoa'
   pod 'RxOptional'
   pod 'YapDatabase'
   pod 'AsyncDisplayKit'
   pod 'ObjectMapper'
   pod 'Moya/RxSwift'
   pod 'Fabric'
   pod 'Crashlytics'
   pod 'Kanna', '~> 2.1.0'

   target 'TransportTests' do
      inherit! :search_paths
   end
   
end
```
Kanna 2.1.0, CocoaPods 1.1.1, XCode 8.2.1
