### ISSUE TITLE
Unresolved identifier in "HTML" 

### ISSUE THREAD

**Issue by clarchiu** [tid-kijyun/Kanna#76]
Hi, I've manually imported Kanna and I'm getting the error code: "Use of unreseolved identifier in 'HTML'". I'm using the Xcode 7.3, I've downloaded the latest version of Kanna (1.0.5). As per your instructions I have not included "import Kanna" in my code. 
![screen shot 2016-06-22 at 2 28 59 pm](https://cloud.githubusercontent.com/assets/20098330/16284379/bac98c94-3885-11e6-986a-8fc79660c799.png)

**Comment by tid-kijyun** [comment]
Are you add the `Kanna.swift` to your project?

**Comment by clarchiu** [comment]
this is what my folders look like
![screen shot 2016-06-28 at 10 57 51 am](https://cloud.githubusercontent.com/assets/20098330/16426748/37139978-3d1f-11e6-8ce9-4fc090fb207a.png)

**Comment by tid-kijyun** [comment]
1. Are you add all files to your **Xcode project**?
![screen shot 2016-06-29 at 3 22 01 am](https://cloud.githubusercontent.com/assets/1665104/16427590/fc619bb0-3da8-11e6-8562-5ea6bab8679f.png)

2. Please try using the version 1.0.6.
https://github.com/tid-kijyun/Kanna/releases/tag/1.0.6

**Comment by tid-kijyun** [comment]
Please let me know if you have any trouble.
