### ISSUE TITLE
How to traverse a document

### ISSUE THREAD

**Issue by zachwaugh** [tid-kijyun/Kanna#83]
Thanks for this library! It looks almost perfect for my needs, but I was looking for a way to traverse the entire document or a sub-tree? I was looking for something along the lines of:

``` swift
protocol XMLDocument {
    var rootNode: XMLElement
}

protocol XMLElement {
    var children: [XMLElement]
}

let doc: HTMLDocument // ... assume this exists

for node in doc.rootNode.children {
  // Do something with node
  // or recursively traverse children nodes
}
```

Is there a way to do that? If not, would you be opposed to adding those methods? I'd be happy to work on that and open a PR.

**Comment by gbuela** [comment]
I was just trying to achieve exactly that and found that it's done with xpath:
```
node.xpath("child::node()").forEach { element in
// here you get node's direct children
}
```
So it's a matter of getting a good xpath reference!

**Comment by zachwaugh** [comment]
I ultimately ended up with a similar solution, but I think this is common enough to be provided as a convenience method by the library. Going to close this issue for now since it's been sitting open over a year.
