### ISSUE TITLE
Issue using Package as dependency

### ISSUE THREAD

**Issue by iksnae** [tid-kijyun/Kanna#87]
### Description:

I'm having an issue installing this package as a dependency. When I execute `swift build`, I get the following error:
`realpath error: No such file or directory (2): https:/github.com/tid-kijyun/Kanna`
### Installation method:
- [*] Swift Package Manager
### Library version:
- [*] v1.1.0
### Xcode version:
- [*] 8.0 beta 2
### Environment:
- [*] DEVELOPMENT-SNAPSHOT-2016-06-06-a
- [*] DEVELOPMENT-SNAPSHOT-2016-06-20-a

Here's what my local package file looks like:
<img width="858" alt="screen shot 2016-07-16 at 8 38 25 am" src="https://cloud.githubusercontent.com/assets/799271/16895593/d665b604-4b30-11e6-8dc9-cbd32a7d016b.png">

**Comment by iksnae** [comment]
here's output in terminal:
<img width="988" alt="screen shot 2016-07-16 at 8 43 58 am" src="https://cloud.githubusercontent.com/assets/799271/16895607/7c1fe39e-4b31-11e6-9582-ae0077cdee6d.png">

**Comment by tid-kijyun** [comment]
This problem was resolved in v2.1.0.
