### ISSUE TITLE
Can't build with xcode 8 beta 3.

### ISSUE THREAD

**Issue by Vladius25** [tid-kijyun/Kanna#89]
### Description:

```
*** Fetching Kanna
*** Checking out Kanna at "ecc112494ca81ad1f8bc3ddd136ad78d09dd2e1b"
*** xcodebuild output can be found in /var/folders/mw/k8n1pfh912v75y_4w153l79h0000gn/T/carthage-xcodebuild.C0cjQE.log
*** Building scheme "Kanna_tvOS" in Kanna.xcworkspace
** CLEAN FAILED **
The following build commands failed:
	Check dependencies
(1 failure)
```
Log:
```
/usr/bin/xcrun xcodebuild -workspace /Users/admin/Documents/Carthage$
    BITCODE_GENERATION_MODE = bitcode
    CARTHAGE = YES
    CODE_SIGN_IDENTITY =
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = appletvos10.0

=== CLEAN TARGET Kanna_tvOS OF PROJECT Kanna WITH CONFIGURATION Release ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configur$

=== BUILD TARGET Kanna_tvOS OF PROJECT Kanna WITH CONFIGURATION Release ===

Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configur$
```

### Installation method:
- [x] Carthage

### Library version:
- [x] v1.1.0

### Xcode version:
- [x] 8.0 beta 3

**Comment by MainasuK** [comment]
Check that:

![2016-07-19 15 42 33](https://cloud.githubusercontent.com/assets/7940186/17084417/a0e122d2-51ef-11e6-9935-b5b04df8820d.png)

Just set it  to NO

**Comment by Vladius25** [comment]
Already NO

**Comment by MainasuK** [comment]
I use CocoaPods with that setting:

pod 'Kanna', :git => 'https://github.com/tid-kijyun/Kanna', :branch => 'swift3.0'

Should not set specific version (1.1.0) in Podfile. But I don't know how to set it correctly in Carthage. Somebody has idea about that?

**Comment by Vladius25** [comment]
I do the same: 

github "tid-kijyun/Kanna" "swift3.0"

Could you give me your kanna.framework please?

**Comment by MainasuK** [comment]
If a workaround is what you find, do manual installation but not copy and paste module. The header will be lost when just copy it. The README offered the method to do that. :)

**Comment by Vladius25** [comment]
There is another issues for OSX:

`CompileSwift normal x86_64
    cd /Users/admin/Documents/rutracker/Carthage/Checkouts/Kanna
    /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -c /U$
/Users/admin/Documents/rutracker/Carthage/Checkouts/Kanna/Sources/libxmlHTMLNode.swift:56:88: error: type 'CompareOpt$
            let inner = html.replacingOccurrences(of: "</[^>]*>$", with: "", options: .regularExpressionSearch, range$
                                                                                       ^~~~~~~~~~~~~~~~~~~~~~~
<unknown>:0: note: did you mean 'NSRegularExpressionSearch'?
`

**Comment by MainasuK** [comment]
Yeah. The same issue in Xcode 8 beta 3.
It's works after chang it to .regularExpression

**Comment by Vladius25** [comment]
Finally it was updated for Xcode 8 beta 4.
