### ISSUE TITLE
ability to click through the website

### ISSUE THREAD

**Issue by mattgolding** [tid-kijyun/Kanna#91]
### Description:
Is there a way to click via Kanna?  I need to move through a website and not just load a page.

### Installation method:
- [x] Carthage
- [ ] CocoaPods
- [ ] Manually

### Library version:
- [x] v1.0.6
- [ ] v1.0.2
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 8.0 beta
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

**Comment by tid-kijyun** [comment]
It's impossible because Kanna is parser.
