### ISSUE TITLE
Unable to Build Kanna 

### ISSUE THREAD

**Issue by Blaster681** [tid-kijyun/Kanna#94]
### Description:
Terminal error result:

The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/Dev/Desktop/nextInpact/Carthage/Checkouts/Kanna/Kanna.xcworkspace -scheme Kanna -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **

The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)

### Installation method:
- [x] Carthage
- [ ] CocoaPods
- [ ] Manually

### Library version:
- [x] v1.0.6
- [ ] v1.0.2
- [ ] other: (Please fill in the version you are using.)

### Xcode version:
- [x] 8.0 beta
- [ ] 7.3.1
- [ ] other: (Please fill in the version you are using.)

On MacOs Sierra

Some idee to resolve this issue?

**Comment by tid-kijyun** [comment]
Do you use Xcode 8.0 beta 6?

**Comment by littlepotatosoftware** [comment]
I'm seeing the same problem with XCode 8 beta 6. I believe the flag to tell Xcode to use the older version of Swift is missing (SWIFT_VERSION = yes).  I opened up the Kanna Xcode Project and upgraded to Swift 2.3, and then added the SWIFT_VERSION build setting to all targets, and it works now.

**Comment by tid-kijyun** [comment]
@Blaster681 @littlepotatosoftware 

Thank you for reporting this issue.
The new version 1.1.1 has been released.

Thanks

**Comment by tid-kijyun** [comment]
Please let me know if you have any trouble.
