### ISSUE TITLE
Swift3

### ISSUE THREAD

**Issue by bevbomb** [tid-kijyun/Kanna#99]
Any news on Swift 3 pods release?

**Comment by PRES1DENT** [comment]
To use Kanna library (CocoaPods) you need add it to your Podfile:

```
use_frameworks!
pod 'Kanna', git: 'https://github.com/tid-kijyun/Kanna.git', branch: 'swift3.0'
```

then in terminal:

```
rm Podfile.lock (if exist)
pod init
pod update
pod install
```
Take tutorial from [here](http://swift-hacks.blogspot.com/2016/09/swift-30-tutorial-how-to-add-framework.html)

**Comment by tid-kijyun** [comment]
I've just released a version 2.0.0 that fixes issues.

Please use Cocoapods 1.1.0RC or later.

```
pod 'Kanna', '~> 2.0.0'
```

**Comment by Arti3DPlayer** [comment]
@tid-kijyun i use `pod 'Kanna', '~> 2.0.0'`

but get error:
```
Module compiled with Swift 2.3 cannot be imported in Swift 3.0: /Users/myname/Library/Developer/Xcode/DerivedData/project-gkpwotjsfhaafgdwagklhjbrfmta/Build/Products/Debug-iphonesimulator/Kanna.framework/Modules/Kanna.swiftmodule/x86_64.swiftmodule```

**Comment by Arti3DPlayer** [comment]
also `pod 'Kanna', git: 'https://github.com/tid-kijyun/Kanna.git', branch: 'swift3.0'` same error :(

**Comment by Arti3DPlayer** [comment]
founds solution: http://stackoverflow.com/questions/39777068/cant-migrate-to-3-0-pods-libraries
